"""
Manual review of the PLUS added text, one sentence per proposal x sub-rubric (written by Claude, no LLM API calls).

Criteria
--------
doc-verifiable : the sentence must address the sub-rubric's topic and state concrete, checkable facts at the
                 score-5 level (named parties, numbers, dates, document or patent IDs). A self-description
                 ("the revenue model is clearly defined") without those facts is not aligned.
judgment-dep   : the sentence must address the sub-rubric's topic and supply the signals an evaluator has to
                 weigh (track record, comparables, market context, how risks are handled), WITHOUT declaring
                 the conclusion ("durable advantage", "well-suited", "realistic"). A bare conclusion is not aligned.
Both           : wrong topic, or an implausible fact for the proposal's domain (e.g. a US regulator for a
                 Chinese product), is not aligned.

Every corrected sentence is FICTIONAL experiment content, like the original PLUS text: company and product
names are invented, and dates, figures, sources and publications are made up. It must not be read as a fact about any proposal or organisation.

Format: REVIEW[dimension][sub_rubric][pid] = (issue, corrected_text)
Any proposal x sub-rubric missing from REVIEW was judged aligned and keeps its original sentence.
"""

REVIEW = {
    "strategy": {
        "strategy_R1_gtm": {
            "p3": ("no contract or evidence, only 'will serve'",
                   "We signed a three-year exclusive distribution contract with BioTech Innovations on 15 March 2026, covering antibody reagent sales to 40 pharmaceutical R&D labs in China, with a minimum purchase commitment of 8 million yuan in year one."),
            "p4": ("describes the partner's revenue, not our contract",
                   "We signed a distribution contract with MedTech Innovations in February 2026 covering 120 tertiary hospitals in eastern China; the first purchase order of 60 units (3.6 million yuan) was delivered in April 2026."),
            "p5": ("no contract or evidence, only 'agreed to act'",
                   "We signed a five-year sales agency contract with AeroTech Solutions in January 2026; its first order of 12 micro-thrusters for two commercial satellite operators (1.8 million yuan) is due for delivery in Q4 2026."),
            "p6": ("no contract or evidence, only 'will serve'",
                   "We signed a channel contract with Zhixing Fleet Services in March 2026 to install our computing platform in its 300 autonomous sweeper and delivery vehicles, and received the first payment of 4.5 million yuan in May 2026."),
            "p8": ("a CDMO is a manufacturer, not a sales channel; no contract",
                   "We signed a commercial distribution agreement with Huaxin Pharma Distribution in April 2026 covering 850 respiratory and infectious-disease hospitals in China, effective on approval, with a minimum annual purchase commitment of 20 million yuan."),
            "pB": ("implausible channel for phone charging chips; no evidence",
                   "We sell directly to phone makers under supply contracts signed in 2025 with two OEMs; our fast-charging chips ship in four phone models, with 2.1 million units and 18 million yuan of revenue in Q1 2026."),
            "pC": ("no contract or evidence, only 'will serve'",
                   "We signed enrolment-partnership contracts with 18 provincial vocational schools in February 2026, which refer graduating students to our colleges; this channel produced 1,240 paid enrolments for the spring 2026 intake."),
        },
        "strategy_R2_milestones": {
            "p2": ("only one milestone, no completion criteria",
                   "Our roadmap has three dated milestones: a prototype enzyme with at least twice the activity of the reference enzyme by Q3 2026, pilot production of 500 kg by Q2 2027, and first commercial shipments to two customers by Q4 2027."),
            "p3": ("no dates or milestones, only a claim",
                   "Our roadmap sets three dated milestones: 20 lead antibody candidates with affinity below 1 nM by Q4 2026, IND-enabling studies for the top candidate completed by Q4 2027, and an IND filing by Q2 2028."),
            "p4": ("no dates or milestones, only a claim",
                   "Our roadmap sets three dated milestones: completion of the 150-patient registration trial by Q4 2026, NMPA Class III approval by Q3 2027, and installation in 20 hospitals by Q2 2028."),
            "p6": ("only one milestone, no completion criteria",
                   "Our roadmap sets three dated milestones: platform prototype passing 1,000 hours of road testing by Q4 2026, deployment in 300 vehicles by Q3 2027, and 2,000 vehicles by Q4 2028."),
            "p8": ("no dates or milestones, only a claim",
                   "Our roadmap sets three dated milestones: GLP toxicology studies completed by Q4 2026, IND filing by Q2 2027, and the first 30 patients dosed in Phase I by Q4 2027."),
            "pA": ("only one milestone, no completion criteria",
                   "Our roadmap sets three dated milestones: IGBT prototype wafers passing reliability qualification by December 2026, pilot-line output of 5,000 wafers per month by Q3 2027, and 20,000 wafers per month by Q4 2028."),
            "pB": ("only one milestone, no completion criteria",
                   "Our roadmap sets three dated milestones: tape-out of the next-generation 100 W charging chip by Q3 2026, qualification with two phone makers by Q1 2027, and shipments of 10 million units by Q4 2027."),
            "pC": ("no dates or milestones, only a claim",
                   "Our roadmap sets three dated milestones: 10 colleges open with 5,000 students by September 2026, 40 colleges by September 2027, and all 100 colleges accredited by September 2029."),
            "pD": ("only one milestone, no completion criteria",
                   "Our roadmap sets three dated milestones: prototype testing completed with at least 95% conversion efficiency by Q1 2027, AEC-Q100 qualification by Q4 2027, and an IPO filing by Q2 2028."),
        },
        "strategy_R3_revenue": {
            "p4": ("no unit economics; 'competitive' is a claim",
                   "Hospitals pay 15,000 yuan per treatment session, billed monthly; each session costs us 5,250 yuan to deliver, a gross margin of 65%."),
            "p5": ("no unit cost or gross margin",
                   "Each micro-thruster sells for $20,000, with 30% paid on order and 70% on delivery; unit cost is $9,000, a gross margin of 55%, and maintenance contracts add $2,000 per unit per year."),
            "p8": ("no unit economics; 'competitive' is a claim",
                   "Each treatment course is priced at $150 and paid through hospital procurement on 90-day terms; cost of goods is $45 per course, a gross margin of 70%."),
            "pC": ("no unit cost or gross margin",
                   "Tuition is $3,000 per student per semester, paid upfront; teaching and facility costs are $1,950 per student, a gross margin of 35%."),
        },
        "strategy_R4_regulatory": {
            "p2": ("vague, no date or reference; FDA unlikely for a Chinese enzyme maker",
                   "We submitted a food-enzyme registration dossier to China's National Health Commission in March 2026 (acceptance no. 2026-E-0412); the technical review decision is expected in Q4 2026."),
            "p5": ("wrong regulator (FAA) for a Chinese satellite component; no date",
                   "We applied for space-product certification with the China National Space Administration in February 2026, and our thruster passed the qualification test review in April 2026."),
            "p6": ("wrong jurisdiction (US NHTSA) for a Chinese vehicle platform",
                   "We filed the product access application for our autonomous-driving computing platform with China's Ministry of Industry and Information Technology in May 2026, and hold road-test permits for 20 vehicles in Beijing."),
            "pA": ("vague: no named body, date, or reference",
                   "Our IGBT modules passed AEC-Q101 qualification in March 2026, and we applied for China Compulsory Certification for the power-module line in April 2026 (application no. 2026-CCC-7781)."),
            "pC": ("vague body and no outcome",
                   "We applied to the provincial Department of Education in April 2026 to establish the first 10 colleges, and received approval for 6 of them in June 2026."),
            "pD": ("wrong regulator: the FDA does not regulate semiconductors",
                   "Our charge-pump chips passed AEC-Q100 Grade 1 qualification in March 2026 and received RoHS and REACH compliance certificates from an accredited test lab in April 2026."),
        },
        "strategy_R5_moat": {
            "p1": ("declares the conclusion ('durable advantage')",
                   "Our heart-failure model is trained on 1.2 million patient records from 14 partner hospitals under exclusive data agreements running to 2030, and one patent on the model architecture was granted in 2025; the two nearest competitors train on public datasets of under 100,000 records."),
            "p2": ("filed patents only; no signals to weigh",
                   "We hold two granted and three pending patents on our enzyme modification method; the leading international supplier uses a different directed-evolution method, and customers who switch supplier must re-validate their production process, which takes 6 to 9 months."),
            "p5": ("declares the conclusion ('durable advantage')",
                   "We hold one granted patent and two pending applications on our propulsion design; our thruster weighs 40% less than the two domestic alternatives, and satellite makers need about 18 months to qualify a new thruster supplier."),
            "p6": ("filed patents only; no signals to weigh",
                   "Our SmartOSEK operating system has run in 50,000 vehicles since 2021; an automaker that switches away needs 12 to 18 months of re-certification, and we hold 12 granted software patents."),
            "pA": ("declares the conclusion ('significant barrier')",
                   "We hold two granted patents and five pending applications on our IGBT process; building a comparable analog production line takes 3 to 4 years and over 2 billion yuan, and our three largest customers each took 12 months to qualify us as a supplier."),
        },
        "strategy_R6_partners": {
            "p3": ("mixes 'discussions' with an agreement; no engagement evidence",
                   "We signed a co-development agreement with the Institute of Biophysics in January 2026, which provides 3 million yuan and screening facilities for our first two antibody programmes."),
            "p8": ("only 'in discussions', no engagement",
                   "We signed a co-development agreement with Huaxin Pharmaceutical in February 2026, which paid a 15 million yuan upfront fee and shares Phase I costs."),
            "pA": ("off-topic: market-position claim, no engagement evidence",
                   "TechDistributors Inc. placed purchase orders worth 12 million yuan in Q1 2026, and we signed a joint-development agreement with an electric-vehicle maker to design a custom IGBT module."),
            "pB": ("off-topic: revenue expectation, no named partner or engagement",
                   "Our two OEM partners co-developed the 100 W charging reference design with us under agreements signed in 2025 and paid 6 million yuan in development fees that year."),
            "pC": ("vague partners, no engagement evidence",
                   "We signed agreements with the governments of three cities in 2026 that provide campus buildings rent-free for 10 years, and a private investor committed 50 million yuan."),
            "pD": ("co-development only 'in discussions'",
                   "We signed a co-development agreement with GreenTech Innovations in March 2026 to design a charge-pump chip for its fast chargers, and received 5 million yuan in development fees on signing."),
        },
        "strategy_R7_team_fit": {
            "p1": ("declares the conclusion ('proven track record') with no specifics",
                   "Professor Zhang Liang led the rollout of a heart-failure care pathway across 30 hospitals in 2019-2022, and the team's commercial lead previously sold hospital software to 200 hospitals."),
            "p2": ("copied from the existing report; no new signals",
                   "Dr. Zhang Lu Jia previously ran enzyme product sales at an industrial biotech firm, growing revenue from 20 to 150 million yuan over five years, and Dr. Feng Yinghui led the scale-up of three enzyme products from lab to 100-ton production."),
            "p5": ("generic claim ('ensuring alignment')",
                   "The CTO spent 12 years designing propulsion systems at a national aerospace institute, including thrusters flown on 8 satellites, and the sales lead previously sold components to 5 commercial satellite makers."),
            "p6": ("generic claim ('well-suited', 'similar projects')",
                   "Yang Guoqing previously led the rollout of a vehicle operating system at two automakers, covering 50,000 vehicles, through the same automaker-integration route this strategy relies on."),
            "p7": ("generic claim ('exceptionally well-suited')",
                   "Dr. Kong Na took two immunotherapy programmes from preclinical work to Phase I at a Shanghai biotech in 2018-2023, and Dr. Tao Wei managed NMPA filings for three oncology drugs."),
            "p8": ("copied from the existing report; no new signals",
                   "The CEO previously led an RNA vaccine programme through IND and Phase I at a mid-sized biotech, and the CSO developed two lipid nanoparticle formulations that reached clinical trials."),
            "pB": ("generic claim ('well-equipped')",
                   "The CEO ran the fast-charging chip business of a domestic chip company from 2015 to 2021, shipping over 1 billion units to phone makers through the same direct-to-OEM route this strategy uses."),
            "pC": ("generic claim ('well-equipped')",
                   "The General Manager previously opened and ran 25 vocational schools for a national education group between 2012 and 2022."),
            "pD": ("generic claim ('well-equipped')",
                   "Two co-founders led power-management chip launches at a listed chip company, taking four products from tape-out to over 50 million units shipped."),
        },
        "strategy_R8_timing": {
            "p1": ("vague catalyst, no evidence",
                   "China's National Health Commission issued national heart-failure treatment guidelines in 2024 and asked tertiary hospitals in 2025 to set up heart-failure centres; over 600 centres were certified by the end of 2025."),
            "p2": ("vague catalyst ('recent regulatory changes')",
                   "China's 2025 biomanufacturing action plan targets a 20% share of bio-based chemicals by 2030, and enzyme purchases by domestic feed and food makers grew 14% in 2025."),
            "p3": ("vague catalyst ('recent regulatory changes')",
                   "An NMPA reform in 2024 cut the review time for innovative biologic IND applications to 30 working days, and Chinese antibody licensing deals exceeded $40 billion in 2025."),
            "p5": ("vague catalyst ('recent regulatory changes')",
                   "Chinese commercial satellite launches rose from 30 in 2022 to over 120 in 2025, and the planned low-orbit constellations of more than 13,000 satellites each need small electric thrusters."),
            "p6": ("vague catalyst; US-style framing for a Chinese product",
                   "Beijing's autonomous-vehicle regulation took effect in April 2025 and allows driverless commercial operation, and over half of new cars sold in China in 2025 had L2+ driver assistance."),
            "p7": ("vague catalyst ('recent regulatory changes')",
                   "NMPA priority review for cancer immunotherapies cut approval times to about 12 months in 2024, and China's immunotherapy market grew 35% in 2025."),
            "p8": ("vague catalyst; US framing for a China-focused product",
                   "Pandemic-preparedness programmes in China and the US began funding broad-spectrum antivirals in 2024, and respiratory-virus hospitalisations in China rose 25% in the 2025-26 winter season."),
            "pA": ("general demand trend with no evidence",
                   "Since 2023, export controls have pushed Chinese EV makers to qualify local IGBT suppliers; China sold 13 million EVs in 2025, while local IGBT supply covered under 40% of demand."),
            "pB": ("vague catalyst ('recent regulatory changes')",
                   "China's unified fast-charging standard (UFCS) took effect in 2024, and major phone makers adopted it in their 2025 models, which require new compatible charging chips."),
            "pD": ("vague catalyst, no named standard or date",
                   "A 2025 national efficiency standard requires chargers to reach 90% efficiency from January 2026, a level older charge-pump designs cannot meet."),
        },
    },
    "objectives": {
        "objectives_R1_problem_clarity": {
            "p2": ("wrong domain: p2 makes tool and industrial enzymes, not therapies; implausible statistic",
                   "Chinese feed and reagent makers import about 60% of their high-purity tool enzymes, and domestic enzymes lose 30-40% of their activity during pelleting at 85°C, which raises customers' enzyme costs by around 25%."),
            "p4": ("vague ('a significant percentage'); problem not quantified",
                   "Of the 1.5 million patients diagnosed with tumours in China each year, about 45,000 have recurrent glioblastoma, for whom second-line chemotherapy extends median survival by only 2 to 3 months."),
            "p5": ("no quantified evidence or specific customer context",
                   "Small-satellite operators in China report that current cold-gas micro-thrusters deliver under 1 mN of thrust and limit orbit-keeping to about 3 years, forcing replacement launches that cost 20 to 30 million yuan per satellite."),
            "p6": ("off-topic: market growth, not the problem",
                   "Autonomous sweeper and delivery vehicles in China need to process data from 12 cameras and 5 lidars within 100 ms, but the embedded computers they use today reach only 60% of that throughput, which forces operators to cap speeds at 15 km/h."),
            "pB": ("off-topic: market size, not the problem",
                   "Phones with 5,000 mAh batteries still take 60 to 90 minutes to charge fully, and charging above 65 W with current chips raises battery temperature beyond 45°C, which shortens battery life by about 20%."),
        },
        "objectives_R2_market_size": {
            "p2": ("global figure only, no addressable segment",
                   "China's enzyme market was worth 12 billion yuan in 2025 (China Biotech Industry Report 2025), of which feed enzymes and research reagent enzymes, our two target segments, account for 3.1 billion yuan."),
            "p3": ("therapeutics market, not our segment; no breakdown",
                   "The global antibody discovery services market was $8.5 billion in 2025 (BioPlan Associates, 2025), of which AI-assisted antibody design, our segment, was $1.2 billion, with China accounting for $300 million."),
            "p8": ("global figure only, no addressable segment",
                   "China's antiviral drug market was 42 billion yuan in 2025 (IQVIA China, 2025), of which respiratory antivirals for hospitalised high-risk patients, our target segment, accounted for 6.8 billion yuan."),
            "pD": ("global figure only, no addressable segment",
                   "The global power-management IC market will reach $45 billion by 2027 (MarketsandMarkets, 2026); charge-pump chips for phone fast chargers, our segment, are $2.4 billion, of which Chinese phone makers buy $900 million."),
        },
        "objectives_R3_buyer_pathway": {
            "p2": ("wrong domain (US medical bodies) and no documented pathway",
                   "Our buyers are feed producers and research-reagent suppliers; a feed group with 40 mills signed a letter of intent in March 2026 for a 6-month trial of 20 tons of our phytase, with a supply contract to follow if it meets agreed activity targets."),
            "p4": ("only 'expressed interest'; no LOI or pilot",
                   "Peking Union Medical College Hospital signed a letter of intent in March 2026 to run a 40-patient pilot of our device, and Shanghai Ruijin Hospital included it in its 2026 equipment procurement list."),
            "p5": ("implausible buyers (US defence firms) and only 'preliminary discussions'",
                   "Two Chinese commercial satellite makers signed letters of intent in 2026 to fly our micro-thruster on 6 demonstration satellites, with a combined order of 60 units planned if the in-orbit test succeeds."),
            "p6": ("implausible buyers and only 'expressed interest'",
                   "A Chinese municipal sanitation operator signed a letter of intent in April 2026 to pilot our computing platform in 50 autonomous sweepers, with a procurement tender planned for Q1 2027."),
            "p7": ("only 'expressed interest'; Sinopharm is not a care provider",
                   "Three tertiary cancer hospitals in Shanghai signed letters of intent in 2026 to join our investigator-initiated trial, and a provincial medical insurance bureau agreed to review the therapy for coverage after approval."),
            "p8": ("implausible buyers (US insurers) and only 'expressed interest'",
                   "Five infectious-disease hospitals in China signed letters of intent in 2026 to take part in our Phase II trial and to list the therapy for procurement after approval."),
            "pA": ("wrong buyers: foundries do not buy IGBT modules",
                   "Two Chinese electric-vehicle makers signed letters of intent in 2026 for pilot orders of 10,000 IGBT modules each, to be delivered after vehicle-level qualification in Q2 2027."),
        },
        "objectives_R4_unmet_need_evidence": {
            "p2": ("wrong domain: patient data for a tool and industrial enzyme company",
                   "A 2025 survey by the China Feed Industry Association found that 68% of feed mills report phytase activity losses above 30% after pelleting, and national feed-phosphorus limits introduced in 2024 require them to use more enzyme."),
            "pC": ("statistic does not show an unmet need",
                   "The provincial human resources bureau reported in 2025 a shortage of 1.2 million skilled technicians, while existing vocational colleges in the region can enrol only 150,000 students a year."),
        },
        "objectives_R5_why_now": {
            "p2": ("refers to a 'regulatory shift' that is never named; declares the conclusion",
                   "From 2024, China's feed-phosphorus limits have required feed mills to cut inorganic phosphate, and domestic phytase demand rose 18% in 2025 as a result."),
            "p3": ("vague catalyst; declares the conclusion ('opportune moment')",
                   "In 2024 NMPA cut the review time for innovative biologic IND applications to 30 working days, and the number of AI-designed antibodies entering clinical trials doubled between 2023 and 2025."),
            "p4": ("vague catalyst; declares the conclusion",
                   "NMPA's innovative medical device special review programme, expanded in January 2026, cut average approval time for Class III devices from 22 to 14 months."),
            "p5": ("wrong regulator (FAA) for a Chinese product",
                   "China's 2024 commercial space measures opened satellite launches to private companies, and domestic commercial launches rose from 30 in 2022 to over 120 in 2025."),
            "p6": ("wrong jurisdiction (US NHTSA) for a Chinese product",
                   "Beijing's autonomous-vehicle regulation of April 2025 allows driverless commercial operation, and 20 more Chinese cities opened driverless test zones in 2025."),
            "p7": ("vague catalyst; declares the conclusion",
                   "In 2024 NMPA added mRNA cancer vaccines to its breakthrough therapy programme, and three mRNA oncology products entered Chinese clinical trials in 2025."),
            "p8": ("vague catalyst; US framing for a China-focused product",
                   "After the 2023-24 respiratory-virus waves, China's 2025 infectious-disease plan created a priority review route for broad-spectrum antivirals, and hospital antiviral purchases rose 22% in 2025."),
            "pA": ("refers to an unnamed 'regulatory insight'; declares the conclusion",
                   "Export controls introduced in 2023 restrict imports of advanced power semiconductors into China, and China's 2024 industrial policy offers a 30% subsidy for domestic IGBT production lines."),
            "pB": ("vague catalyst; declares the conclusion",
                   "China's unified fast-charging standard (UFCS) took effect in 2024, and phone makers representing 80% of domestic shipments committed to adopt it in 2025 models."),
            "pC": ("refers to unnamed 'data' and a vague 'regulatory push'",
                   "The revised Vocational Education Law took effect in 2022, and the 2026 provincial budget raised funding for vocational colleges by 25%."),
        },
        "objectives_R6_competitive_context": {
            "p1": ("no named alternatives; declares the conclusion",
                   "The two main heart-failure management tools in Chinese hospitals, a paper-based guideline checklist and a commercial risk calculator, flag high-risk patients 3 to 5 days before readmission; our model flagged them 14 days earlier in a 2,000-patient retrospective test."),
            "p2": ("named products but no differentiating evidence",
                   "Compared with the two leading imported phytases, our enzyme kept 85% of its activity after pelleting at 85°C versus 55% and 60%, and costs 30% less per ton of feed."),
            "p4": ("generic alternatives; declares the conclusion",
                   "Compared with second-line chemotherapy for recurrent glioblastoma, which gives a median survival of 6 months with 30% grade 3 side effects, our device showed a median survival of 9 months with 8% grade 3 side effects in a 120-patient study."),
            "p5": ("named competitors but no differentiation",
                   "Compared with the two nearest products, the Orbitek MT-1 and a domestic institute's CG-2, our micro-thruster gives 2 mN of thrust at 180 g versus 1 mN at 300 g, and costs about half as much."),
            "p7": ("generic alternatives; declares the conclusion",
                   "Compared with PD-1 inhibitors, which give a 15% response rate in our target tumours, our mRNA therapy achieved a 32% response rate in a 40-patient early study."),
            "p8": ("named products but no differentiating evidence",
                   "Compared with the standard intravenous antiviral, which in our animal study delivered 5% of the dose to lung tissue, our inhaled lipid nanoparticle delivered 40% of the dose to the lungs in animal studies."),
            "pA": ("no named alternative; unclear comparison",
                   "Compared with the two leading imported IGBT modules, the Veltron VM450 and Kessler K45, our module showed 20% lower switching losses in third-party tests and is priced 30% lower."),
            "pC": ("no named competitors or evidence",
                   "Compared with the region's three largest vocational colleges, where 55% of graduates find jobs in their field, our pilot programme placed 82% of its first 300 graduates in related jobs."),
            "pD": ("named competitors but no differentiation",
                   "Compared with the closest charge-pump chips, the Corvex CP970 and Altima AP3200, ours reach 96% conversion efficiency versus 92% and 93%, in a package 30% smaller."),
        },
        "objectives_R7_problem_solution_fit": {
            "p1": ("declares the conclusion ('explicit', 'seamlessly'); no mechanism",
                   "Our model predicts readmission risk from routine discharge data and sends a treatment-adjustment alert to the cardiologist, which targets the 30-day readmissions described above; in a pilot ward, readmissions fell from 30% to 21%."),
            "p2": ("declares the conclusion; refers to patient deficiencies (wrong domain)",
                   "Our redesigned phytase has three stabilising mutations that keep 85% of its activity at 85°C pelleting temperatures, where current enzymes lose 30-40% of their activity."),
            "p3": ("declares the conclusion; no mechanism",
                   "Our platform predicts binding affinity before synthesis, so labs test 50 candidates instead of 2,000, which cuts the design cycle from 12 months to 4."),
            "p5": ("no mechanism; refers to an unnamed 'gap'",
                   "Our thruster uses a miniaturised electrospray design that produces twice the thrust per gram of cold-gas systems, which extends orbit-keeping from 3 to 7 years and removes the need for replacement launches."),
            "p6": ("declares the conclusion; no mechanism",
                   "Our platform runs sensor fusion on a dedicated chip that processes 12 camera and 5 lidar feeds within 60 ms, which lets vehicles run at 30 km/h instead of the current 15 km/h limit."),
            "p7": ("declares the conclusion ('robust'); mechanism vague",
                   "Our mRNA encodes tumour antigens together with an immune-activating cytokine, which restores T-cell activity in tumours that do not respond to PD-1 inhibitors."),
            "pA": ("fit with policy, not with the stated problem",
                   "Our 12-inch IGBT process uses a field-stop design that lowers switching losses, which lets Chinese EV makers replace imported modules without redesigning their inverters."),
            "pB": ("declares the conclusion; no mechanism",
                   "Our chip splits charging across two cells and adjusts voltage every 10 ms based on battery temperature, which allows 100 W charging while keeping the battery below 40°C."),
            "pC": ("mechanism not linked to the stated problem",
                   "Each programme is designed with local employers and includes a 6-month paid placement; 60% of graduates of existing colleges in the region report being unprepared for work."),
            "pD": ("declares the conclusion ('tight'); mechanism vague",
                   "Our chip uses a switched-capacitor design with adaptive frequency control, which cuts conversion losses at light loads, where most power is wasted in current chargers."),
        },
        "objectives_R8_addressability": {
            "p2": ("wrong domain (US patients) for a Chinese tool and industrial enzyme company",
                   "We will start with the 300 largest feed mills in eastern China, which buy 40% of domestic phytase, and aim to supply 30 of them within three years, about 2,000 tons a year."),
            "p6": ("vague entry point; reach not realistic",
                   "We will start with municipal sanitation and campus delivery fleets in 5 cities, about 6,000 vehicles, and aim to equip 1,500 of them within three years."),
            "p7": ("no reach estimate or entry mechanism",
                   "We will start in 15 tertiary cancer centres in eastern China, which treat about 40,000 advanced solid tumour patients a year, and aim to treat 2,000 patients within three years of approval."),
            "p8": ("entry point vague; reach not tied to it",
                   "We will start in 50 infectious-disease hospitals that admit about 300,000 high-risk respiratory patients a year, and aim to treat 30,000 of them in the first two years after approval."),
            "pA": ("vague entry point and segment",
                   "We will start with the four Chinese EV makers that buy 55% of domestic IGBT modules, and aim to supply 10% of their demand, about 400,000 modules a year, within three years."),
            "pB": ("no entry point; segment too broad",
                   "We will start with the three Chinese phone makers that already sampled our chips, which ship 200 million phones a year, and aim to be in 20 million of them by 2028."),
            "pC": ("no segment size or reach estimate",
                   "We will start in the two provinces with the largest technician shortage, where 400,000 school leavers choose vocational training each year, and aim to enrol 20,000 students within three years."),
        },
    },
    "advantages": {
        "advantages_R1_mechanism_novelty": {
            "p3": ("off-topic: about patents, no mechanism described",
                   "Our platform designs antibody binding loops with a generative model conditioned on the target's 3D epitope, instead of screening random libraries, which is a different mechanism from phage display and hybridoma methods."),
            "p4": ("vague ('unique electromagnetic field modulation'); no technical specifics",
                   "Our second-generation device applies alternating electric fields at 200 kHz from four switching electrode arrays, which rotate the field direction every second to disrupt tumour cell division in all planes, unlike first-generation devices with two fixed directions."),
            "p5": ("claim of novelty with no mechanism",
                   "Our micro-thruster uses electrospray ionisation of an ionic liquid propellant, with 64 emitters etched on a silicon chip, rather than the pressurised cold gas used in current small-satellite thrusters."),
            "p6": ("vague ('novel approach'); no mechanism",
                   "SmartOSEK schedules perception and control tasks on a single time-triggered kernel that shares memory between CPU and AI accelerator, instead of the separate message-passing layers used by AUTOSAR systems."),
            "p7": ("claim of novelty with no mechanism",
                   "Our circular mRNA is closed by a self-splicing ribozyme, which removes the free ends that cells use to degrade linear mRNA and extends protein expression from 2 days to 7."),
            "p8": ("no technical specifics ('proprietary formulation process')",
                   "Our lung-targeted nanoparticles add a cationic lipid at 20% molar ratio that binds lung endothelial cells, a composition our AI model selected from 5,000 candidates, unlike standard liver-targeting MC3 formulations."),
            "pA": ("claim of a new class with no mechanism",
                   "Our IGBT uses a trench-gate field-stop structure on 12-inch wafers with a thinned 60 µm drift layer, which lowers conduction losses compared with planar-gate designs."),
            "pC": ("vague; no mechanism described",
                   "Our colleges assign each student a weekly learning plan generated from their quiz results and workplace-supervisor ratings, so theory lessons are reordered around the skills each student is missing."),
            "pD": ("refers to an unnamed 'differentiation'; no mechanism",
                   "Our charge pump switches between 1:1, 2:1 and 3:1 capacitor ratios every cycle based on load current, instead of using a fixed ratio like conventional charge pumps."),
        },
        "advantages_R2_ip_status": {
            "p1": ("no patent numbers or status",
                   "We hold granted Chinese patent CN115123456B (granted November 2025) on our heart-failure risk model, and two applications, CN202610234567.8 and CN202610234568.6, filed in January 2026, are under examination."),
            "pC": ("no application numbers or status",
                   "We filed two Chinese invention patents on our adaptive learning system, CN202610345678.1 and CN202610345679.X, in February 2026, and registered software copyright 2026SR0123456 in March 2026."),
        },
        "advantages_R3_performance_proof": {
            "p4": ("no comparator for the 45% figure",
                   "In a 12-week preclinical study in 40 animals, tumours treated with our device shrank by 45%, compared with 18% for first-generation devices under the same protocol."),
            "p6": ("no named benchmark or method",
                   "In a 500-hour road test on 20 vehicles, SmartOSEK processed sensor data 30% faster and used 25% less energy than the AUTOSAR-based system in the same vehicles, measured with the same test routes and loads."),
            "p7": ("no figures at all",
                   "In a mouse model of melanoma (n = 10 per group), our circular mRNA reduced tumour volume by 68% after 21 days, compared with 43% for the linear mRNA of the same antigen."),
            "pC": ("no comparator or method",
                   "In a one-semester pilot with 300 students, scores on the national vocational skills test rose by 25% compared with 300 students in a matched class taught with the standard curriculum."),
        },
        "advantages_R4_competitor_benchmark": {
            "p1": ("named competitor but no metrics",
                   "In a 2,000-patient retrospective test, our model predicted 30-day readmission with an AUC of 0.84, compared with 0.71 for HeartTrack Pro on the same patients."),
            "p4": ("no competitor named and no metrics",
                   "In a 100-patient head-to-head study published in March 2026, our device gave a 6-month progression-free rate of 52%, compared with 38% for the leading first-generation tumour-treating-fields device."),
            "p6": ("named competitor but no metrics",
                   "On the same 12-camera workload, SmartOSEK on our board completed a perception cycle in 58 ms at 45 W, compared with 82 ms at 65 W on the leading imported board, the Arvix DX2."),
            "p7": ("no competitor named",
                   "In the same mouse model, our circular mRNA reduced tumour volume by 25% more than the linear mRNA vaccine of a leading competitor, BioNova's BNV-101."),
            "pA": ("no competitor named",
                   "In third-party tests in March 2026, our IGBT module had 15% lower switching losses and 20% lower thermal resistance than the leading imported module, the Veltron VM450, at the same current rating."),
            "pB": ("placeholder competitor name ('XYZ Corp')",
                   "In tests on the same phone, our chip charged a 5,000 mAh battery to 100% in 28 minutes, compared with 37 minutes for the leading competitor's chip, the Sunlink SL65, and the battery kept 15% more capacity after 800 cycles."),
            "pC": ("compares with an industry average, not a named competitor",
                   "Our course completion rate is 85%, compared with 70% at the region's largest vocational college, Jiangnan Vocational Institute, over the same 2025-26 year."),
            "pD": ("placeholder competitor name ('XYZ product')",
                   "In the same test setup, our charge pump reached 95% efficiency at 2 A, compared with 72% for the leading competitor's chip, the Corvex CP970."),
        },
        "advantages_R5_defensibility": {
            "p3": ("vague ('strategic partnerships'); no signals to weigh",
                   "Our design model is trained on 150,000 antibody-antigen structures, including 40,000 from the Institute of Biophysics that we can use exclusively until 2031, and we hold two granted patents on the design method."),
            "p4": ("declares the conclusion ('durable moat', 'ensuring')",
                   "Our three patents run to 2045 and cover the switching electrode design; competitors would also need a new 150-patient trial and about 3 years for NMPA Class III approval to launch a similar device."),
            "p5": ("vague ('strong IP protection, exclusive partnerships')",
                   "We hold one granted patent on the emitter chip, our ionic-liquid propellant comes from the only domestic supplier under a 5-year exclusive contract, and satellite makers take about 18 months to qualify a new thruster."),
            "p6": ("vague ('strong IP protections, exclusive partnerships')",
                   "We hold 12 granted software patents, SmartOSEK is certified to ISO 26262 ASIL-D, which took us 3 years, and two automakers have signed 5-year exclusive supply agreements."),
            "p7": ("vague ('strong IP protection, exclusive partnerships')",
                   "Our granted patent on ribozyme-based circularisation runs to 2044, and our only GMP manufacturing partner has agreed not to produce circular mRNA for other companies until 2030."),
            "p8": ("restates partners already in the report; no terms to weigh",
                   "We hold a granted US patent on the lung-targeting lipid, and our two manufacturing partners signed exclusive supply agreements for that lipid running to 2032."),
            "pA": ("LOIs are not exclusivity; implausible partners",
                   "Two Chinese EV makers have signed 5-year exclusive supply agreements for our IGBT module, and each switch of supplier requires about 12 months of vehicle-level requalification."),
            "pB": ("placeholder partner names; no terms",
                   "Our chip firmware is tied to the charging protocols of two phone makers under 3-year exclusive agreements signed in 2025, and switching chip supplier requires 9 months of safety recertification."),
            "pC": ("declares the conclusion ('robust network effect')",
                   "Our 120 partner employers take our graduates for placements under 5-year agreements, and each new employer adds placement slots that attract more students, which in turn attracts more employers."),
            "pD": ("placeholder partner names; no terms",
                   "We hold three pending patents, and our two largest distributors, Wintech Components and Hua Rong Electronics, signed 3-year exclusive agreements for charge-pump chips in 2026."),
        },
        "advantages_R6_platform_potential": {
            "p1": ("claim ('can support multiple applications') without validated applications",
                   "The same model architecture, retrained on hospital data, predicted 30-day readmission for COPD with an AUC of 0.81 and for diabetes with 0.79 in 2025 validation studies at two partner hospitals."),
            "p3": ("claim ('can be adapted') without validated applications",
                   "Our design platform has also produced two nanobodies and one enzyme inhibitor that met their binding targets in 2025 lab tests, besides our antibody candidates."),
            "p4": ("claim ('designed to be adaptable') without validated applications",
                   "Besides glioblastoma, our device is in clinical studies for pancreatic cancer (60 patients) and mesothelioma (40 patients), using the same field generator with different electrode arrays."),
            "p5": ("claim ('can be adapted') without validated applications",
                   "The same emitter chip has been tested for satellite attitude control and for drag compensation on a CubeSat, both in 2025 ground tests at a national aerospace lab."),
            "p6": ("claim ('can be adapted') without validated applications",
                   "SmartOSEK already runs in passenger-car domain controllers, in autonomous sweepers, and in port container trucks, with deployments at three customers in 2025."),
            "p7": ("claim ('can be adapted') without validated applications",
                   "The same circularisation method produced an infectious-disease vaccine candidate that reached neutralising antibody targets in mice, and a protein-replacement mRNA now in preclinical testing."),
            "p8": ("claim ('can be adapted') without validated applications",
                   "The same lung-targeted nanoparticle delivered a gene-editing payload in a cystic fibrosis mouse model and an RNA vaccine in a 2025 animal study."),
            "pA": ("applications named but not validated",
                   "Our IGBT process already supplies modules for solar inverters (1,200 units shipped in 2025) and industrial motor drives (800 units), besides the automotive modules in qualification."),
            "pB": ("applications named but not validated",
                   "The same chip architecture ships in tablets and laptop chargers, with 300,000 units sold in 2025, and an e-bike charger version passed customer tests in March 2026."),
            "pC": ("claim ('capacity to expand') without validated applications",
                   "The same learning system is used in our corporate training courses for two manufacturers and in an online adult-education programme with 3,000 learners."),
            "pD": ("applications named but not validated",
                   "The same charge-pump design is used in wireless earbuds and smartwatch chargers, with 2 million units shipped in 2025, and an automotive version is in AEC-Q100 qualification."),
        },
        "advantages_R7_validation_signals": {
            "p1": ("LOIs show adoption intent, not external validation",
                   "Our readmission model was published in the Chinese Journal of Cardiology in January 2026, and received NMPA Class II software registration in March 2026."),
            "p3": ("off-topic: about collaboration, not validation",
                   "Our design method was published in Nature Communications in 2025, and a pharmaceutical company paid 5 million yuan for antibodies designed with it."),
            "p4": ("an LOI from a drug company does not validate a device",
                   "Our device received NMPA innovative medical device designation in February 2026, and our preclinical results were published in the Journal of Cancer Research in March 2026."),
            "p6": ("wrong jurisdiction (US NHTSA) for a Chinese product",
                   "SmartOSEK received ISO 26262 ASIL-D certification from an accredited certification body in 2025, and our vehicles received public-road test permits from the Beijing transport authority in May 2026."),
            "p7": ("conference acceptance is weak validation",
                   "Our preclinical results were published in Molecular Therapy in 2025, and NMPA accepted our IND application in April 2026."),
            "pB": ("LOIs show adoption intent, not external validation",
                   "Our chip passed UFCS compliance testing by the China Academy of Information and Communications Technology in 2025, and a phone maker has paid for 2 million units."),
            "pD": ("wrong authority: the FCC does not approve charge-pump chips",
                   "Our charge-pump chip passed AEC-Q100 qualification in March 2026, and a charger maker paid for its first 500,000 units in April 2026."),
        },
        "advantages_R8_adoption_readiness": {
            "p5": ("only 'active discussions' for pilots",
                   "A commercial satellite maker signed a pilot contract in March 2026 to fly our thruster on two satellites launching in early 2027, with an option for 40 more units."),
            "pD": ("placeholder client names",
                   "Pilots are under way with two charger makers, Lianchuang Power and Haoyu Electronics, which signed purchase agreements for 1 million units each on successful completion of the pilot."),
        },
    },
    "team": {
        "team_R1_composition": {
            "p1": ("adds one person; does not show all critical roles filled",
                   "Professor Zhang Liang leads clinical direction, Dr. Chen Wei (CTO) leads model development, Li Na (COO) runs hospital operations, and Wang Tao (commercial director) leads hospital sales."),
            "p2": ("adds one person; does not show all critical roles filled",
                   "Dr. Zhang Lu Jia (CEO) leads commercial strategy, Dr. Feng Yinghui (CTO) leads enzyme R&D and scale-up, Zhou Min (production manager) runs the pilot plant, and Xu Hao (sales director) manages feed and reagent customers."),
            "p3": ("vague; no named people or roles",
                   "Professor Wang Jiangyun (chief scientist) leads antibody design, Dr. Li Hua (CTO) runs the AI platform, Dr. Sun Jie leads wet-lab validation, and Ma Lin (business development director) manages pharmaceutical partners."),
            "p4": ("vague; no named people or roles",
                   "Dr. Palti (chairman) leads commercial strategy, Dr. Liu Yang (CTO) leads device engineering, Dr. Gao Fei (medical director) runs clinical trials, and Zhao Rui (regulatory director) manages NMPA filings."),
            "p5": ("adds one person; does not show all critical roles filled",
                   "Dr. Wu Qiang (CEO) leads the company, Dr. Han Lei (CTO) leads thruster design, Zhu Yan (test director) runs qualification testing, and Lin Bo (sales director) manages satellite-maker accounts."),
            "p6": ("names one role only",
                   "Yang Guoqing (CTO) leads platform development, Dr. Xu Ming (CEO) leads fundraising and strategy, Chen Jing (safety director) runs functional-safety certification, and Liu Kai (sales director) manages fleet operators."),
            "p7": ("names one role only",
                   "Dr. Kong Na (principal investigator) leads research, Dr. Tao Wei (regulatory director) manages NMPA filings, Dr. Shen Yu (CMC director) runs mRNA manufacturing, and Huang Li (business director) handles licensing."),
            "p8": ("names two people; roles incomplete",
                   "Dr. Zhou Jian (CEO) leads the company, Dr. Qian Rong (CSO) leads nanoparticle formulation, Dr. He Bin leads AI modelling, Dr. Yu Fang (clinical director) runs trials, and Deng Hao (CFO) manages finance."),
            "pA": ("vague; no named people or roles",
                   "Lee Wen (CEO) leads the company, Dr. Guo Peng (CTO) leads IGBT process development, Xie Dan (fab director) runs the production line, and Tang Wei (sales director) manages automotive customers."),
            "pB": ("names one role only",
                   "Dr. Mei Chen (CEO) leads the company, Dr. Luo Jun (CTO) leads chip design, Cao Ying (operations director) manages foundry supply, and Pan Hui (sales director) manages phone-maker accounts."),
            "pC": ("vague; no named people or roles",
                   "The General Manager, Song Tao, runs operations, Dr. Ye Lan (academic director) leads curriculum, Fang Qi (employer relations director) manages placements, and Jiang Wen (CFO) manages finance."),
            "pD": ("names one role only",
                   "Dr. Ren Hao (CEO) leads the company, Dr. Du Xin (CTO) leads charge-pump design, Zhang Liye (legal director) manages IP and compliance, and Qin Yue (sales director) manages charger-maker accounts."),
        },
        "team_R2_credentials": {
            "p5": ("vague ('multiple papers'); truncated",
                   "Dr. Han Lei holds a PhD in propulsion engineering from Beihang University, has 18 papers on electric propulsion, and holds 6 granted patents on micro-thruster design."),
            "p6": ("off-topic: describes an outcome, not credentials",
                   "Yang Guoqing holds a PhD in automotive engineering from Tsinghua University, has 25 papers on vehicle operating systems, and holds 9 granted patents on in-vehicle computing."),
            "pA": ("declares the conclusion ('impressive'); vague patents",
                   "Dr. Guo Peng holds a PhD in microelectronics from Fudan University, has 14 IEEE papers on power devices, and holds 11 granted patents on IGBT structures."),
            "pD": ("legal and FDA credentials are not the project's domain",
                   "Dr. Du Xin holds a PhD in electrical engineering from Zhejiang University, has 12 papers in IEEE Transactions on Power Electronics, and holds 8 granted patents on charge-pump circuits."),
        },
        "team_R3_track_record": {
            "p4": ("no named products or outcomes",
                   "Dr. Palti's previous company launched three devices between 2019 and 2024, including the NeuroField 1, which reached 40 hospitals and 60 million yuan in annual sales."),
            "p5": ("implausible (NASA Mars Rover) for a Chinese team",
                   "Dr. Han Lei led development of the cold-gas thruster flown on the Tianyan-3 satellite in 2021, which has kept orbit for 5 years."),
            "p6": ("unnamed product",
                   "Yang Guoqing led the launch of the NaviCore navigation system in 2020, which is installed in 50,000 vehicles and earned 120 million yuan in 2024."),
            "p7": ("unnamed and implausible product",
                   "Dr. Kong Na led the development of the IMV-201 cancer vaccine at a Shanghai biotech, which entered Phase II in 2023 after a 45-patient Phase I."),
            "p8": ("unnamed product; 'groundbreaking' is a claim",
                   "Dr. Zhou Jian previously led the flu antiviral FluStop through NMPA approval in 2022 at a mid-sized biotech; it reached 200 million yuan in sales in 2024."),
            "pB": ("vague; no named project or outcome",
                   "Dr. Mei Chen led the launch of the PowerOne 65 W charging chip at a previous company in 2020, which shipped 300 million units by 2023."),
        },
        "team_R4_governance": {
            "p1": ("named advisors but no decision structure or agreements",
                   "Our board has five members, including two independent directors; major decisions need board approval, and our two advisors, Dr. Liu Feng and Ms. Zhang Mei, have signed 3-year advisory agreements with 0.5% equity each."),
            "p2": ("named advisors but no decision structure or agreements",
                   "Our board has three members plus an investor observer and meets quarterly; advisors Dr. Sarah Thompson and Mr. David Lee have signed 2-year advisory agreements, and the founders' equity split is set out in a signed shareholders' agreement."),
            "p3": ("decision structure but no named board or advisors",
                   "Our four-member board, chaired by Professor Wang Jiangyun, approves budgets over 1 million yuan; advisors Dr. Hu Ping and Dr. Li Qing have signed advisory agreements, and IP ownership is set out in an agreement with the university."),
            "p4": ("decision structure but no named board or agreements",
                   "Our board, chaired by Dr. Palti, has five members including a hospital director and two investors; a signed shareholders' agreement sets out voting rights, and our clinical advisory board of three named oncologists meets quarterly."),
            "p5": ("one name only; no structure or agreements",
                   "Our board has four members, chaired by Dr. Wu Qiang, and approves all contracts over 2 million yuan; advisors Dr. Robert Smith and Professor Zhao Heng have signed 2-year advisory agreements with equity options."),
            "p6": ("named advisors but no decision structure or agreements",
                   "Our five-member board includes two investor directors and approves the annual plan; advisors Dr. Zhang Li and Mr. Chen Feng have signed advisory agreements, and founder shares vest over four years."),
            "p7": ("no named advisors; 'ensuring' is a claim",
                   "Our board of four is chaired by Dr. Kong Na; advisors Dr. Lucas Brandt, a former mRNA programme lead, and Professor Yang Hong have signed advisory agreements, and a scientific committee reviews each programme before the next stage."),
            "p8": ("named advisors but no decision structure or agreements",
                   "Our board has five members and approves all trial starts; advisors Dr. Michael Thompson and Dr. Lisa Wong have signed 3-year advisory agreements with equity options, and a shareholders' agreement sets out founder vesting."),
            "pA": ("names only; 'robust' is a claim",
                   "Our five-member board approves capital spending over 5 million yuan; advisors Dr. Robert Smith and Ms. Linda Wong have signed advisory agreements, and a shareholders' agreement sets out investor voting rights."),
            "pB": ("one name; 'robust' is a claim",
                   "Our board of five, chaired by Dr. Mei Chen, approves product roadmaps; advisors Dr. Anna Wu and Professor Xu Li have signed 2-year advisory agreements, and employee equity is held in a formal share plan."),
            "pC": ("agreements but no named advisors or structure",
                   "Our board of four approves new college openings; advisors Professor Liang Yu, a former vocational college president, and Ms. Zhou Hong, an HR director, hold 0.3% equity each under signed advisory agreements."),
            "pD": ("decision structure but no named board or agreements",
                   "Our board of five, chaired by Dr. Ren Hao, approves tape-outs and budgets; advisors Professor Wang Kai and Ms. Chen Lu have signed advisory agreements, and a shareholders' agreement is in place ahead of the planned IPO."),
        },
        "team_R5_capacity": {
            "p1": ("hiring plan vague; no team size or commitment",
                   "The team has 9 full-time staff, and Professor Zhang Liang spends 40% of his time on the project; we plan to hire 2 clinical coordinators and 2 data analysts by Q1 2027 for the 30-hospital rollout."),
            "p3": ("no team size or commitment; 'comprehensive' is a claim",
                   "The team has 14 full-time staff, and Professor Wang Jiangyun works on the project two days a week; we plan to hire 2 bioinformatics specialists by Q4 2026."),
            "p4": ("vague; no team size or commitment",
                   "The team has 18 full-time staff, including 8 engineers, and Dr. Palti works on the project half-time; we plan to hire 2 engineers and a clinical trial manager by Q1 2027."),
            "p5": ("vague; truncated",
                   "The team has 11 full-time staff, 7 of them engineers; we plan to hire 3 test engineers by mid-2027, when production reaches 20 thrusters a year."),
            "p7": ("vague; declares the conclusion ('well-equipped')",
                   "The team has 10 full-time staff, and Dr. Kong Na works on the project full-time; we plan to hire a regulatory affairs manager and a market-access lead by Q2 2027, before the IND filing."),
            "pB": ("no base headcount; '30%' has nothing to refer to",
                   "The team has 40 full-time staff, 28 of them chip designers; we plan to hire 12 more engineers over the next 12 months for the 100 W chip programme."),
        },
        "team_R6_complementarity": {
            "p1": ("declares the conclusion ('evident', 'balanced')",
                   "Professor Zhang Liang covers cardiology, Dr. Chen Wei covers machine learning, and Wang Tao has 10 years of hospital software sales; no one on the team has medical-device regulatory experience, which we cover through an external consultant."),
            "p2": ("declares the conclusion ('positions us well')",
                   "Dr. Feng Yinghui covers enzyme engineering and Dr. Zhang Lu Jia covers sales and finance; the team has no feed-industry specialist yet, and one is included in the 2026 hiring plan."),
            "p3": ("off-topic: about roles and responsibilities",
                   "Professor Wang Jiangyun covers structural biology, Dr. Li Hua covers machine learning, and Ma Lin has 8 years of pharmaceutical business development; the team has no clinical development expert."),
            "p4": ("off-topic: about regulation and delivery",
                   "Dr. Liu Yang covers device engineering, Dr. Gao Fei covers oncology, Zhao Rui covers NMPA regulation, and Dr. Palti covers commercialisation; manufacturing is outsourced to a contract manufacturer."),
            "p5": ("declares the conclusion; truncated",
                   "Dr. Han Lei covers propulsion physics, Zhu Yan covers space qualification testing, and Lin Bo has sold to satellite makers for 6 years; the team has no in-house production engineer yet."),
            "p6": ("off-topic: about the hiring plan",
                   "Yang Guoqing covers vehicle software, Chen Jing covers functional safety, and Liu Kai covers fleet sales; the team currently has no AI chip hardware designer and relies on a supplier for the board."),
            "p7": ("off-topic: about responsibilities",
                   "Dr. Kong Na covers tumour immunology, Dr. Shen Yu covers mRNA manufacturing, and Dr. Tao Wei covers regulation; the team has no clinical operations lead and uses a contract research organisation."),
            "p8": ("declares the conclusion ('evident', 'no critical gaps')",
                   "Dr. Qian Rong covers nanoparticle formulation, Dr. He Bin covers AI modelling, and Dr. Yu Fang covers clinical trials; the team has no manufacturing lead, and GMP production is outsourced."),
            "pA": ("declares the conclusion ('balanced', 'without any significant gaps')",
                   "Dr. Guo Peng covers device physics, Xie Dan has 15 years of fab operations, and Tang Wei covers automotive sales; the team has no automotive quality-certification specialist yet."),
            "pB": ("declares the conclusion ('evident')",
                   "Dr. Luo Jun covers analog chip design, Cao Ying covers foundry supply, and Pan Hui covers phone-maker sales; the team relies on an external lab for battery safety testing."),
            "pC": ("off-topic: about the hiring plan",
                   "Song Tao has 10 years of school operations, Dr. Ye Lan covers curriculum design, and Fang Qi covers employer partnerships; the team has no online-learning technology lead yet."),
            "pD": ("declares the conclusion ('evident', 'balanced')",
                   "Dr. Du Xin covers power IC design, Zhang Liye covers IP and compliance, and Qin Yue covers charger-maker sales; the team has no in-house test engineer and uses an external lab."),
        },
        "team_R7_cohesion": {
            "p1": ("vague initiative; declares the conclusion",
                   "Professor Zhang Liang and Dr. Chen Wei jointly built the hospital's heart-failure registry in 2020-2023, which now holds 60,000 patient records."),
            "p4": ("off-topic: about regulation and delivery",
                   "Dr. Palti, Dr. Liu Yang and Zhao Rui worked together at Dr. Palti's previous company from 2017 to 2023 and jointly launched the NeuroField 1 device."),
            "p5": ("vague; truncated",
                   "Dr. Han Lei and Zhu Yan worked together for 8 years at a national aerospace institute and jointly delivered the thruster for the Tianyan-3 satellite in 2021."),
            "p6": ("refers to an unnamed 'history of joint success'",
                   "Yang Guoqing, Chen Jing and Liu Kai worked together at the same automaker from 2016 to 2022 and jointly launched the NaviCore navigation system in 2020."),
            "p7": ("off-topic: about responsibilities",
                   "Dr. Kong Na and Dr. Tao Wei worked together at a Shanghai biotech from 2018 to 2023 and jointly took the IMV-201 vaccine into Phase II."),
            "p8": ("vague; no named project or outcome",
                   "Dr. Zhou Jian and Dr. Qian Rong worked together for 6 years and jointly took the FluStop antiviral from formulation to NMPA approval in 2022."),
            "pB": ("vague; no named project or outcome",
                   "Dr. Mei Chen, Dr. Luo Jun and Cao Ying worked together at the same chip company for 7 years and jointly launched the PowerOne 65 W chip in 2020."),
            "pC": ("refers to unnamed 'experience'; declares the conclusion",
                   "Song Tao, Dr. Ye Lan and Fang Qi worked together at the same education group from 2014 to 2022 and jointly opened 25 vocational schools."),
        },
        "team_R8_key_person_risk": {
            "p1": ("restates the rubric wording without concrete mechanisms",
                   "Dr. Chen Wei can run model development without Professor Zhang Liang, a second cardiologist, Dr. Xu Jing, co-leads the clinical work, and founders' shares vest over four years."),
            "p2": ("generic mentorship statement; no concrete backup",
                   "Dr. Feng Yinghui's enzyme methods are documented in standard procedures and a second scientist, Dr. Qi Wen, can run them; founders' shares vest over four years."),
            "p3": ("declares the conclusion ('no single individual is irreplaceable')",
                   "Professor Wang Jiangyun spends two days a week on the project, and Dr. Li Hua can run the design platform without him; key staff hold options that vest over four years."),
            "p4": ("declares the conclusion ('robust succession plan')",
                   "Dr. Liu Yang is the named successor to Dr. Palti for technical decisions, the company holds key-person insurance of 10 million yuan on both, and their shares vest over four years."),
            "p5": ("restates the rubric wording; truncated",
                   "Two engineers besides Dr. Han Lei can run thruster qualification tests, and the three founders' shares vest over four years with a one-year cliff."),
            "p6": ("generic knowledge-sharing statement; no concrete backup",
                   "Chen Jing can lead platform releases in Yang Guoqing's absence, the company holds key-person insurance on Yang Guoqing, and his shares vest over four years."),
            "p8": ("restates the rubric wording without mechanisms",
                   "Dr. He Bin can lead formulation work if Dr. Qian Rong leaves, all formulation data is held in the company's own records, and key staff options vest over four years."),
            "pA": ("generic mentorship statement; no concrete backup",
                   "Each production step has two qualified operators, Xie Dan's deputy can run the fab, and the founders' shares vest over five years."),
            "pB": ("restates the rubric wording without mechanisms",
                   "Three senior designers besides Dr. Luo Jun have led tape-outs, and key engineers hold options that vest over four years."),
            "pC": ("generic mentorship statement; no concrete backup",
                   "Each college has a deputy principal who can run it, Dr. Ye Lan's curriculum is held in a shared library, and the founders' shares vest over four years."),
            "pD": ("restates the rubric wording without mechanisms",
                   "Two senior designers besides Dr. Du Xin have led charge-pump tape-outs, and the founders and key engineers hold shares that vest over four years."),
        },
    },
    "feasibility": {
        "feasibility_R1_budget_detail": {
            "p4": ("says a breakdown exists but gives no amounts",
                   "The 25 million yuan angel round is allocated over 24 months: 10 million yuan for the registration trial, 7 million for device engineering, 5 million for staff, and 3 million for regulatory and operating costs."),
            "p5": ("says a breakdown exists but gives no amounts",
                   "The $2.5 million budget over three years is allocated as $1.1 million for thruster development, $600,000 for qualification testing, $500,000 for staff, and $300,000 for launch-slot and operating costs."),
            "p7": ("says a breakdown exists but gives no amounts",
                   "The 35.2 million yuan budget over three years is allocated as 15 million yuan for preclinical studies, 9.2 million for GMP manufacturing, 7 million for staff, and 4 million for regulatory filings and operations."),
            "p8": ("off-topic: describes funding, not the budget breakdown",
                   "The total budget of $2.8 million over 24 months is allocated as $1.2 million for toxicology studies, $800,000 for GMP nanoparticle batches, $500,000 for staff, and $300,000 for regulatory and operating costs."),
            "pA": ("says a breakdown exists but gives no amounts",
                   "The planned 260 billion yuan investment over five years is allocated as 150 billion yuan for production lines, 60 billion for R&D, 30 billion for staff, and 20 billion for sales and operations."),
        },
        "feasibility_R2_funding_secured": {
            "p2": ("implausible funder (US NSF) for a Chinese company",
                   "We received a 1.5 million yuan grant from the Jiangsu Provincial Science and Technology Department in March 2026, and an angel investor signed a 5 million yuan investment agreement in April 2026."),
            "p3": ("implausible funder (US NIH SBIR) for a Chinese company",
                   "We received a 3 million yuan grant from the National Natural Science Foundation of China in January 2026, and closed a 10 million yuan seed round in March 2026."),
            "p5": ("implausible funder (NASA SBIR) for a Chinese company",
                   "We closed an 8 million yuan angel round led by a commercial-space fund in March 2026, and received a 2 million yuan municipal innovation grant in April 2026."),
            "p6": ("implausible funder (US NSF); no date",
                   "We closed a 20 million yuan Series A round in February 2026, and received a 3 million yuan Beijing autonomous-driving pilot grant in April 2026."),
            "p8": ("US SBIR funding for a China-focused company",
                   "We closed a 30 million yuan Series A round in March 2026, and received a 5 million yuan grant from the national major new drug development programme in April 2026."),
            "pD": ("implausible funder (US NSF SBIR) for a Chinese company",
                   "We closed a 15 million yuan pre-IPO round in March 2026, and received a 2 million yuan provincial integrated-circuit grant in April 2026."),
        },
        "feasibility_R3_infrastructure": {
            "p2": ("implausible facility (UC Berkeley) for a Chinese company",
                   "We lease a 600 m² fermentation lab in the Nanjing biotech park under a 5-year lease signed in 2025, and have a signed agreement to use a partner's 10-ton pilot fermenter."),
            "p5": ("implausible facilities (MIT, Caltech) for a Chinese company",
                   "We own a vacuum test chamber and thrust stand installed in 2025, and have a signed agreement to use a national aerospace lab's environmental test facility."),
            "p6": ("partners 'will grant' access; nothing confirmed",
                   "We own a 20-vehicle test fleet and a hardware-in-the-loop test lab, and have a signed agreement to use a closed test track in Beijing for 200 days a year."),
            "pA": ("access 'will' be provided; nothing confirmed",
                   "We signed a 5-year capacity agreement in 2026 with a Shanghai foundry for 3,000 wafers a month, and own a packaging and test line installed in 2025."),
            "pB": ("placeholder supplier names",
                   "We have a signed wafer supply agreement with a Chinese foundry for 20,000 wafers a year and a packaging contract with Hengxin Packaging, and own a 300 m² test lab."),
            "pD": ("names competitors as suppliers; no confirmed access",
                   "We have a signed foundry agreement for 12,000 wafers a year on a 180 nm BCD process, and own a reliability test lab with 40 burn-in boards."),
        },
        "feasibility_R4_technical_readiness": {
            "p3": ("vague ('promising results'); no figures or maturity level",
                   "Our design platform is at TRL 5: in 2025 it designed 30 antibodies, of which 12 bound their targets with affinity below 10 nM in lab tests."),
            "p5": ("vague ('promising results'); no figures or maturity level",
                   "Our thruster prototype is at TRL 6: it passed 1,000 hours of vacuum firing and vibration tests in March 2026, delivering 2 mN of thrust."),
            "pA": ("vague; no figures or maturity level",
                   "Our IGBT platform is at TRL 7: pilot wafers produced in 2025 reached 92% yield and passed 1,000-hour high-temperature reliability tests."),
            "pC": ("vague ('positive feedback'); no figures",
                   "Our learning platform has run for one semester in three schools with 900 students; 88% of lessons were completed and skills-test pass rates rose from 61% to 76%."),
        },
        "feasibility_R5_risk_mitigation": {
            "p1": ("lists risks but no mitigation",
                   "Regulatory delay is the main risk; we have booked a pre-submission meeting with NMPA and budgeted 6 extra months. Data privacy risk is handled by keeping all patient data on hospital servers and an external security audit each year."),
            "p2": ("lists risks but no mitigation",
                   "The main risk is weak customer uptake; we will run paid trials with 5 feed mills before scaling. If registration is delayed, we can sell to reagent customers first, as their products need no registration."),
            "p3": ("lists challenges but no mitigation",
                   "If our lead antibodies fail validation, we have 18 backup candidates. To limit competitive risk, we focus on two targets with no approved antibody and file patents before publishing."),
            "p4": ("one contingency; no named risks ('comprehensive' is a claim)",
                   "If the registration trial enrolls slowly, we will add three hospitals already under agreement. If NMPA review is delayed, our budget covers 9 extra months of operations."),
            "p5": ("lists risks but no mitigation",
                   "For component supply risk, we have qualified two valve suppliers. For integration risk, we test each thruster with the customer's satellite bus in our chamber before delivery."),
            "p7": ("mitigation strategies not described",
                   "To reduce regulatory delay, we hold a pre-IND meeting with NMPA before filing. To reduce supply risk, we have qualified two GMP manufacturers and keep 6 months of lipid stock."),
            "pA": ("mitigation strategies not described",
                   "To handle price swings, 60% of our output is sold under fixed-price annual contracts. To reduce supply risk, we keep 4 months of wafer stock and have qualified a second silicon supplier."),
            "pB": ("mitigation strategies not described",
                   "To reduce supply risk, we have qualified two foundries for each chip. To handle price competition, our cost per chip is 20% below the market leader, which leaves room to cut prices."),
            "pC": ("mitigation strategies not described",
                   "If construction is delayed, the first colleges will open in leased buildings already identified. To avoid staff shortages, we train 60 teachers a year in our own programme."),
        },
        "feasibility_R6_resource_timeline_fit": {
            "p1": ("restates the rubric wording; no resources or dates",
                   "The 30-hospital rollout by Q4 2027 needs 6 implementation staff; we have 4 and will hire 2 by Q1 2027, and each 2-person team takes about 6 weeks per hospital; the rollout window is 18 months."),
            "p2": ("restates the rubric wording; no resources or dates",
                   "Pilot production by Q2 2027 depends on the partner's fermenter, which is booked for us from January 2027; our 3 process engineers can run two batches a month, which reaches 500 kg in 5 months."),
            "p3": ("restates the rubric wording; no resources or dates",
                   "IND-enabling studies by Q4 2027 need 14 months of contract research; the contract is signed, and our 6 scientists can produce 2 antibody batches a month against the 10 batches the studies require."),
            "p4": ("restates the rubric wording; no resources or dates",
                   "The 150-patient trial by Q4 2026 needs 5 sites enrolling 3 patients a month each; 4 sites are active, and the fifth opens in September 2026."),
            "p5": ("restates the rubric wording; no resources or dates",
                   "Delivering 12 thrusters by Q4 2026 needs 2 test engineers running one chamber test a week; we have 2, and each thruster needs about 3 weeks from assembly to test."),
            "p6": ("restates the rubric wording; no resources or dates",
                   "Deploying 300 vehicles by Q3 2027 needs 8 field engineers installing 25 vehicles a month; we have 5 and will hire 3 by March 2027."),
            "p8": ("declares the conclusion ('meticulously crafted')",
                   "The Q2 2027 IND filing depends on 12 months of toxicology studies starting in June 2026; the contract research slot is booked, and our 4 formulation scientists can supply the required batches by May 2026."),
            "pB": ("restates the rubric wording; no resources or dates",
                   "Tape-out by Q3 2026 needs 20 designers for 9 months; we have 18 and will hire 2 more by May 2026, and the foundry slot is booked for August 2026."),
            "pC": ("restates the rubric wording; no resources or dates",
                   "Opening 10 colleges by September 2026 needs 150 teachers; we have 110 trained and 60 more finish training in July 2026."),
            "pD": ("target date (June 2024) is already in the past",
                   "AEC-Q100 qualification by Q4 2027 needs 6 months of reliability testing starting in Q2 2027; our test lab has capacity for it, and 2 test engineers join in March 2027."),
        },
        "feasibility_R7_financial_realism": {
            "p1": ("claims benchmarking but names no comparables",
                   "Two comparable hospital AI projects in China spent 18 and 22 million yuan to reach 30 hospitals; our budget is 17 million yuan, and our cash covers 20 months, past the 30-hospital milestone at month 18."),
            "p2": ("claims benchmarking but names no comparables",
                   "Two domestic enzyme start-ups spent 12 and 15 million yuan to reach pilot production; our budget is 13 million yuan, and our cash covers 22 months, past the pilot milestone at month 15."),
            "p3": ("claims benchmarking but names no comparables",
                   "Three Chinese AI antibody start-ups spent 15 to 25 million yuan to reach their first IND; our budget to IND is 18 million yuan, and our cash covers 26 months, past the IND filing at month 24."),
            "p4": ("claims benchmarking but names no comparables",
                   "Two comparable Class III devices in China cost 20 and 28 million yuan to reach approval; our 25 million yuan angel round covers 24 months, past the planned approval at month 20."),
            "p5": ("claims benchmarking but names no comparables",
                   "Two domestic micro-thruster start-ups spent $2 million and $3 million to reach first flight; our budget is $2.5 million, and our cash covers 30 months, past the first flight at month 18."),
            "p6": ("names no comparables",
                   "Two Chinese autonomous-driving platform start-ups spent 25 and 40 million yuan to reach a 300-vehicle deployment; our budget is 30 million yuan, and our cash covers 20 months, past the mid-2027 public demonstration."),
            "p7": ("claims benchmarking but names no comparables",
                   "Two Chinese mRNA oncology start-ups spent 30 and 45 million yuan to reach IND; our budget is 35.2 million yuan, and our cash covers 30 months, past the planned IND at month 24."),
            "p8": ("names no comparables",
                   "Two antiviral start-ups spent $2.5 million and $3.2 million on IND-enabling work; our budget is $2.8 million, and our cash covers 18 months, past the IND filing at month 14."),
            "pA": ("claims benchmarking but names no comparables",
                   "Two comparable 12-inch power-device lines in China cost 180 and 240 billion yuan; our planned investment is 260 billion yuan, and committed funds cover the first 3 years of construction."),
            "pB": ("claims benchmarking but names no comparables",
                   "Two domestic charging-chip companies spent $4 million and $6 million to bring a new chip to volume production; our budget is $5 million, and our cash covers 24 months, past volume shipments at month 18."),
            "pC": ("claims benchmarking but names no comparables",
                   "Two private vocational college groups spent $0.4 to $0.6 million per college to open; our budget is $0.5 million per college, and our cash covers the first 10 colleges and 18 months of operation."),
            "pD": ("claims benchmarking but names no comparables",
                   "Two domestic power-IC companies spent $2 million and $3 million to qualify a new chip; our budget is $2.5 million, and our cash covers 20 months, past AEC-Q100 qualification at month 15."),
        },
        "feasibility_R8_sustainability": {
            "p2": ("wrong buyers (pharmaceutical companies) for tool and feed enzymes; only 'potential'",
                   "Sales of reagent enzymes to 40 lab customers brought in 3 million yuan in 2025, and a feed group's supply contract from 2027 is worth 8 million yuan a year, which covers our operating costs."),
            "p3": ("'expressed interest' only; declares the conclusion",
                   "Two pharmaceutical companies pay us 4 million yuan a year in total for antibody design services under 3-year contracts signed in 2025, which covers 60% of our operating costs."),
            "p4": ("vague ('anticipate'); no mechanism with evidence",
                   "Hospitals will pay 15,000 yuan per session after approval, and 20 hospitals have agreed to buy the device, which we expect to cover operating costs from 2028; until then the angel round covers costs."),
            "p5": ("only 'exploring'",
                   "Our two satellite-maker contracts bring 4 million yuan a year from 2027, and maintenance fees add 1 million yuan, which covers our 5 million yuan annual operating costs."),
            "p6": ("only 'exploring'",
                   "Our fleet contracts bring 18 million yuan a year from 2027 as licence fees of 6,000 yuan per vehicle, which covers our operating costs."),
            "p7": ("licensing model stated without evidence",
                   "A pharmaceutical company signed a licensing option in 2026 with a 10 million yuan upfront fee and milestone payments, which funds operations until the Phase I results."),
            "p8": ("licensing model stated without evidence",
                   "Our co-development partner pays 15 million yuan upfront and shares Phase I costs, and a royalty of 8% on sales is agreed in the signed contract."),
            "pA": ("only 'pursuing' funding",
                   "Our existing solar and motor-drive module sales bring 900 million yuan a year, and MIIT confirmed a 3 billion yuan grant for the production line in 2026."),
            "pB": ("vague revenue model; no evidence",
                   "Chip sales brought 72 million yuan in 2025 with a 45% gross margin, which already covers our operating costs."),
            "pC": ("mechanism listed but only 'potential'",
                   "Tuition from 5,000 students brings 30 million yuan a year, and the provincial government has committed 8 million yuan a year in subsidies until 2030."),
            "pD": ("declares the conclusion ('robust', 'positions us well')",
                   "Chip sales brought 45 million yuan in 2025, and a signed licensing agreement adds 3 million yuan a year, which covers our operating costs."),
        },
    },
}
