# -*- coding: utf-8 -*-
"""
Stage 1 - Chunk-level fact extractor (extract_facts_by_chunk.py)
----------------------------------------------------
Input:
  - src/data/prepared/<proposal_id>/full_text.txt  (generated by prepare_proposal_text.py)

Output:
  - src/data/extracted/<proposal_id>/raw_facts.jsonl  one JSON fact per line

Responsibilities:
  - Split long text into overlapping character-based chunks.
  - Ask the LLM to extract atomic facts from each chunk.
  - Attach dimensions[], type, and meta(chunk_index, char_range) to each fact.
  - Stage 2 later uses these facts to build dimensions_v2.json across five dimensions.

Current extraction design:
  1. Use smaller chunks and larger overlap to improve per-chunk coverage.
  2. Ask the prompt to cover all five dimensions, not only one topic.
  3. Use assertive type-to-dimensions mapping so cross-dimensional facts are visible to multiple dimensions.
  4. Infer dimensions from keywords when the LLM omits or under-specifies labels.
  5. Print fact count distributions at the end and warn about dimensions with very few facts.
  6. Retry dense extraction when a long chunk produces too few facts.
"""

import os
import json
import argparse
import re
import time
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import List, Dict, Any

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.backend.utils.llm_provider import UnifiedChatClient, active_provider, default_model

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

load_dotenv()

# ========= Path configuration =========

BASE_DIR = Path(__file__).resolve().parents[2]
PREPARED_DIR = BASE_DIR / "src" / "data" / "prepared"
EXTRACTED_DIR = BASE_DIR / "src" / "data" / "extracted"
PROGRESS_FILE = BASE_DIR / "src" / "data" / "step_progress.json"


def _write_progress(done: int, total: int, pid: str = "") -> None:
    try:
        path = PROGRESS_FILE.parent / f"step_progress_{pid}.json" if pid else PROGRESS_FILE
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps({"done": done, "total": total}), encoding="utf-8")
    except Exception:
        pass

PROVIDER = active_provider()
OPENAI_MODEL = default_model(PROVIDER)
OPENAI_TIMEOUT_SECONDS = float(os.getenv("OPENAI_TIMEOUT_SECONDS", "120"))
STAGE1_CHUNK_WORKERS = int(os.getenv("STAGE1_CHUNK_WORKERS", "4"))
PREVIEW_CHARS = int(os.getenv("STAGE1_PREVIEW_CHARS", "320"))
LOW_FACT_WARN_THRESHOLD = int(os.getenv("STAGE1_LOW_FACT_WARN_THRESHOLD", "3"))
DEDUP_EXACT_FACTS = os.getenv("STAGE1_DEDUP_EXACT_FACTS", "true").strip().lower() == "true"

# Reuse one global configured-provider client to avoid recreating it for every chunk.
client = UnifiedChatClient(provider=PROVIDER, model=OPENAI_MODEL)

VALID_DIMENSIONS = ["team", "objectives", "strategy", "innovation", "feasibility"]
VALID_TYPES = [
    "team_member",
    "org_structure",
    "collaboration",
    "resource",
    "pipeline",
    "milestone",
    "market",
    "tech_route",
    "product",
    "ip_asset",
    "evidence",
    "budget_item",
    "funding_source",
    "risk",
    "mitigation",
    "ai_model",
    "clinical_design",
    "regulatory",
    "other",
]


# ========= Diagnostic logging =========

def _safe_console_text(text: object) -> str:
    """
    Make log text safe for Windows consoles that cannot print some Unicode characters.
    Keeps the pipeline running even when PDF/Word text contains private-use symbols.
    """
    s = str(text)
    enc = getattr(sys.stdout, "encoding", None) or "utf-8"
    return s.encode(enc, errors="replace").decode(enc, errors="replace")


def _log(level: str, message: str) -> None:
    safe_message = _safe_console_text(message)
    print(f"[{level}] {safe_message}", flush=True)


def _bounded_worker_count(value: int, minimum: int, maximum: int) -> int:
    try:
        parsed = int(value)
    except Exception:
        parsed = minimum
    return max(minimum, min(parsed, maximum))


def _preview_text(text: str, limit: int = PREVIEW_CHARS) -> str:
    text = str(text or "")
    text = text.replace("\uf0b7", "•")
    text = " ".join(text.split())
    if not text:
        return "<empty>"
    if len(text) <= limit:
        return text
    return text[:limit] + " ..."


def _normalize_fact_text(text: str) -> str:
    """
    Normalize fact text for cleanup and duplicate detection.

    The goal is not to rewrite the fact, only to remove layout noise that tends
    to appear in chunked extraction, such as bullets, repeated whitespace, and
    trailing punctuation jitter.
    """
    text = str(text or "").replace("\uf0b7", "•")
    text = " ".join(text.split()).strip()
    text = re.sub(r"^[•\-–—]+\s*", "", text)
    text = re.sub(r"^(?:\[\s*)?(?:fact|point|note)\s*\d*[:\].-]*\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\s+([,.;:!?])", r"\1", text)
    text = re.sub(r"([,;:!?]){2,}$", r"\1", text)
    return text.strip()


def _count_values(items: List[str]) -> Dict[str, int]:
    counts = {}
    for item in items:
        counts[item] = counts.get(item, 0) + 1
    return counts


def _fact_distribution(facts: List[Dict[str, Any]]) -> Dict[str, Dict[str, int]]:
    dims = []
    types = []
    primary_dims = []
    suspect_numeric = 0
    for fact in facts:
        if not isinstance(fact, dict):
            continue
        types.append(fact.get("type", "other"))
        primary_dims.append(fact.get("primary_dimension", "unknown"))
        if fact.get("meta", {}).get("suspect_numeric"):
            suspect_numeric += 1
        for dim in fact.get("dimensions", []):
            dims.append(dim)
    return {
        "dimensions": _count_values(dims),
        "types": _count_values(types),
        "primary_dimensions": _count_values(primary_dims),
        "suspect_numeric": {"count": suspect_numeric},
    }


def _print_input_diagnostics(proposal_id: str, full_text: str, max_chars: int, overlap: int) -> None:
    _log("STAGE1", "Starting chunk-level fact extraction")
    _log("STAGE1", f"proposal_id={proposal_id}")
    _log("STAGE1", f"model={OPENAI_MODEL} max_chars={max_chars} overlap={overlap}")
    _log("STAGE1", f"input_chars={len(full_text)} input_lines={len(full_text.splitlines())}")
    _log("PREVIEW", f"full_text_preview={_preview_text(full_text)}")
    if not full_text.strip():
        _log("WARN", "full_text.txt is empty; Stage 1 will produce no facts.")


def _print_chunk_plan(chunks: List[Dict[str, Any]]) -> None:
    lengths = [ch["end"] - ch["start"] for ch in chunks]
    _log("STAGE1", f"chunk_count={len(chunks)}")
    if lengths:
        _log(
            "STAGE1",
            f"chunk_chars min={min(lengths)} max={max(lengths)} "
            f"avg={sum(lengths) / len(lengths):.1f}"
        )
    for ch in chunks[:5]:
        _log(
            "CHUNK_PLAN",
            f"chunk={ch['index']+1}/{len(chunks)} range={ch['start']}:{ch['end']} "
            f"chars={ch['end'] - ch['start']} preview={_preview_text(ch['text'], 180)}"
        )
    if len(chunks) > 5:
        _log("CHUNK_PLAN", f"... {len(chunks) - 5} more chunk(s) omitted from plan preview")


# Prompt: minimize hallucination, maximize five-dimension coverage, and preserve JSON structure.
FACT_PROMPT = """
You are a fact extractor. Your job is to extract atomic facts, one by one, from a short proposal text chunk.

Critical constraints:
1. Process only the current text chunk. Do not infer content from other pages or external context.
2. Do not invent any institution, person, company, partner, customer, country, city, domain term, product name,
   technology name, model name, project name, market size, user count, beneficiary count, CAGR, or other concrete number.
3. Do not use speculative language such as "may", "likely", "generally", "typically", "usually",
   "probably", "potentially", or "it is believed that", unless that wording appears in the source text
   and you are faithfully restating it.
4. Every fact must be traceable to the source text. You may lightly paraphrase, but preserve key source
   phrases such as product names, service names, technology names, institution names, pipeline names, domain terms, and model names.
5. Keep each fact to 1-2 sentences whenever possible. Be specific and verifiable.
6. Do not repeat the same fact in slightly different wording within the same response.

Target domain:
- Any business, startup, research, product, service, platform, operating, public-sector, nonprofit, infrastructure,
  education, healthcare, manufacturing, software, finance, consumer, logistics, energy, agriculture, or mixed proposal.
- Do not assume a specific domain, customer type, business model, regulated pathway, or delivery model unless it is present in the text.

Definition of an atomic fact:
- A fact should express one relatively independent statement that can stand alone.
- Do not merge many topics into one long sentence.
- If one sentence mentions both team composition and a milestone timeline, split it into two facts.
- If one sentence contains multiple important ideas, such as team background plus technical route plus target market,
  split it into multiple facts.

High-priority content:
- If the text introduces a project team, core members, leaders, CEO, COO, co-founders, operators, professors, specialists,
  or similar people, split each member's information into multiple facts when possible. Capture at least:
  - role or identity plus affiliated institution;
  - main business, operating, research, product, service, or domain area;
  - project-relevant experience or success cases.
- If the text contains market analysis, such as market size, CAGR, growth rate, regional share,
  competitors, sales, customer/user/beneficiary groups, buyer/payer/funder groups, or competitive landscape, split every important number and conclusion
  into separate facts and label them with type="market".

Extraction quantity and granularity:
- Split long sentences into multiple facts so each fact focuses on one topic.
- If the chunk is information-rich, try to extract 15-25 facts.
- If the chunk has little information, fewer than 10 facts or even an empty list is acceptable.
- The maximum number of facts is 25. Do not exceed 25 facts.

Dimension labels:
- "team": facts about teams, people, institutions, roles, responsibilities, and collaboration.
- "objectives": overall goals, staged goals, KPIs, pipeline goals, and subproject goals.
- "strategy": technical route, clinical route, regulatory route, collaboration strategy, commercial strategy,
  market-entry strategy, and operating model.
- "innovation": technical, product, or business-model novelty; comparison with existing approaches;
  patents, unique resources, and evidence advantages.
- "feasibility": resources, budget, funding, implementation path, risks and mitigations, timeline,
  reimbursement or payment environment, and execution practicality.

Dimension tagging requirements:
- If a fact clearly relates to any dimension above, include that dimension in dimensions.
- One fact may belong to multiple dimensions, such as ["team", "strategy"].
- Every fact must include at least one dimension. If uncertain, use ["feasibility"] as the fallback.
- Prefer adding relevant dimensions over leaving a related fact under-labeled.

Allowed type values:
- "team_member": a member's identity, institution, research direction, or project role.
- "org_structure": team or company structure, division of work, or staffing proportions.
- "collaboration": international collaboration, academic-industry collaboration, or cross-region coordination.
- "resource": laboratories, platforms, data, partner resources, or similar assets.
- "pipeline": a pipeline or subproject goal, indication, or technical route.
- "milestone": a concrete task or milestone for a stage, including time information.
- "market": market size, CAGR, target countries/customers, market drivers, or competitive landscape.
- "tech_route": technical, algorithmic, or experimental route.
- "product": product/platform form or business model.
- "ip_asset": patents, proprietary technology, unique datasets, or other IP assets.
- "evidence": animal, clinical, real-world, or other evidence and its conclusions.
- "budget_item": budget amount or cost structure for a stage or purpose.
- "funding_source": funding source, such as internal funds, VC, grants, or partnerships.
- "risk": technical, market, funding, regulatory, AI, or other risks and uncertainties.
- "mitigation": mitigation or response measures for risks.
- "ai_model": a specific AI model, algorithm, or architecture.
- "clinical_design": clinical trial or validation design, including phase, enrollment, and endpoints.
- "regulatory": regulatory path, ethics approval, registration strategy, reimbursement, or payment policy.
- "other": a project-relevant fact that does not fit the other types.

Tagging hints:
- Market size, CAGR, target countries/customers, competitors, payment, or reimbursement usually maps to
  type "market" or "regulatory".
- Funding, budget, cost, and staged investment usually map to "budget_item" or "funding_source".
- Risks, uncertainties, bottlenecks, and challenges map to "risk".
- Responses to risks or problems map to "mitigation".
- Specific AI models, algorithms, or architectures map to "ai_model".
- Patent numbers, PCT filings, core IP, or unique datasets map to "ip_asset".
- If unsure about type, use "other", but choose the closest specific type when possible.

Dimension coverage requirement:
- If the chunk contains multiple kinds of information, such as team, objectives, technical or commercial strategy,
  innovation, feasibility, or risk, try to ensure the extracted facts cover those dimensions.
- Do not concentrate all facts in one dimension while ignoring other relevant content in the same chunk.
- When you need to prioritize, keep facts that represent different dimensions and themes rather than repeatedly
  refining the same minor point.

Output format:
- Return a JSON object with exactly one top-level key: "facts".
- "facts" must be an array of fact objects.
- Each fact object must use this shape:
  {
    "text": "A natural-language fact, preferably 1-2 specific sentences.",
    "dimensions": ["team", "strategy"],
    "type": "team_member"
  }
- Do not output a meta field. The system adds metadata automatically.
- If the current chunk contains no useful facts, return {"facts": []}.
- Do not output explanations or comments. Output JSON only.
Now process the text chunk below.
"""


def find_latest_prepared_proposal() -> str:
    if not PREPARED_DIR.exists():
        raise FileNotFoundError(f"Prepared directory not found: {PREPARED_DIR}")

    candidates = []
    for d in PREPARED_DIR.iterdir():
        if d.is_dir():
            candidates.append((d.stat().st_mtime, d.name))

    if not candidates:
        raise FileNotFoundError(f"No proposal subdirectories found under prepared directory: {PREPARED_DIR}")

    proposal_id = max(candidates, key=lambda x: x[0])[1]
    _log("INFO", f"[auto] selected latest prepared proposal_id={proposal_id}")
    return proposal_id


def load_full_text(proposal_id: str) -> str:
    path = PREPARED_DIR / proposal_id / "full_text.txt"
    if not path.exists():
        raise FileNotFoundError(f"full_text.txt does not exist: {path}")
    text = path.read_text(encoding="utf-8")
    _log("INFO", f"loaded full_text path={path} chars={len(text)}")
    return text


def make_chunks(text: str, max_chars: int = 1800, overlap: int = 400) -> List[Dict[str, Any]]:
    """
    Split text into overlapping character-based chunks; this does not split by sentence.
    The default max_chars=1800 and overlap=400 keep chunks dense enough for good coverage.
    Returns a list where each item contains text, start, end, and index.
    """
    chunks = []
    n = len(text)
    if n == 0:
        return chunks

    idx = 0
    chunk_idx = 0
    while idx < n:
        end = min(n, idx + max_chars)
        chunk_text = text[idx:end]
        chunks.append(
            {
                "index": chunk_idx,
                "start": idx,
                "end": end,
                "text": chunk_text,
            }
        )
        chunk_idx += 1
        if end == n:
            break
        idx = max(0, end - overlap)

    _log("INFO", f"created chunks count={len(chunks)} max_chars={max_chars} overlap={overlap}")
    return chunks


def call_llm_for_chunk(
    chunk_text: str,
    attempt: int = 1,
    dense: bool = False,
    trace: Dict[str, Any] | None = None,
) -> Dict[str, Any]:
    """
    Call OpenAI to extract facts from one chunk.
    - attempt > 1: retry after invalid JSON, with stricter JSON instructions.
    - dense = True: second-pass extraction for long chunks that produced too few facts.
    """
    extra_hint_parts = []

    if attempt > 1:
        extra_hint_parts.append(
            "Important: your previous JSON response was too long or invalid and could not be parsed. "
            "This time, limit facts to at most 18 items and ensure the JSON syntax is valid."
        )

    if dense:
        extra_hint_parts.append(
            "Important: this text chunk is information-rich. In this extraction pass, cover all key facts "
            "related to team, objectives, strategy, innovation, and feasibility. Prefer 15-22 facts when "
            "the source supports them, and cover different dimensions and themes instead of one narrow area."
        )

    extra_hint = ""
    if extra_hint_parts:
        extra_hint = "\n\n" + "\n".join(extra_hint_parts)

    messages = [
        {
            "role": "system",
            "content": "You are a rigorous fact extractor. Extract atomic facts only from the given text chunk. Do not invent facts.",
        },
        {
            "role": "user",
            "content": FACT_PROMPT
            + extra_hint
            + "\n\n=== Text chunk starts ===\n"
            + chunk_text.strip(),
        },
    ]

    call_start = time.perf_counter()
    mode = "dense" if dense else "normal"
    _log(
        "LLM",
        f"call_start mode={mode} attempt={attempt} chunk_chars={len(chunk_text)} "
        f"prompt_chars={sum(len(m.get('content', '')) for m in messages if isinstance(m.get('content'), str))}"
    )
    try:
        resp = client.chat.completions.create(
            model=OPENAI_MODEL,
            messages=messages,
            response_format={"type": "json_object"},
            temperature=0.0,
            max_tokens=1800,
        )
    except Exception as e:
        elapsed = time.perf_counter() - call_start
        _log("ERROR", f"LLM call failed mode={mode} attempt={attempt} elapsed_sec={elapsed:.2f}: {e}")
        if trace is not None:
            trace.setdefault("llm_calls", []).append(
                {
                    "mode": mode,
                    "attempt": attempt,
                    "elapsed_sec": round(elapsed, 2),
                    "ok": False,
                    "error": str(e),
                }
            )
        raise

    raw = resp.choices[0].message.content
    elapsed = time.perf_counter() - call_start
    usage = getattr(resp, "usage", None)
    usage_data = None
    if usage is not None:
        usage_data = {
            "prompt_tokens": getattr(usage, "prompt_tokens", None),
            "completion_tokens": getattr(usage, "completion_tokens", None),
            "total_tokens": getattr(usage, "total_tokens", None),
        }
    _log(
        "LLM",
        f"call_done mode={mode} attempt={attempt} elapsed_sec={elapsed:.2f} "
        f"raw_chars={len(raw or '')} usage={json.dumps(usage_data, ensure_ascii=False)}"
    )
    if trace is not None:
        trace.setdefault("llm_calls", []).append(
            {
                "mode": mode,
                "attempt": attempt,
                "elapsed_sec": round(elapsed, 2),
                "ok": True,
                "raw_chars": len(raw or ""),
                "usage": usage_data,
            }
        )
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        _log("WARN", f"JSON parse failed mode={mode} attempt={attempt}: {e}")
        _log("WARN", f"raw_response_preview={_preview_text(raw or '', 1000)}")
        if trace is not None:
            trace["json_parse_failed"] = True
        if attempt == 1:
            _log("INFO", "retrying chunk with stricter JSON instruction")
            return call_llm_for_chunk(chunk_text, attempt=2, dense=dense, trace=trace)
        # If the second attempt still fails, surface the parsing error.
        raise e

    if not isinstance(data, dict):
        data = {"facts": []}
    if "facts" not in data or not isinstance(data["facts"], list):
        data["facts"] = []

    _log("LLM", f"parsed_facts mode={mode} attempt={attempt} count={len(data['facts'])}")
    return data

# ===== Market keyword helpers =====

_MARKET_EN = [
    "market", "market size", "market volume", "market demand", "market potential",
    "target market", "segment", "niche",
    "market share", "penetration",
    "customer", "customers", "client", "clients",
    "user", "users", "buyer", "buyers", "payer", "payers",
    "beneficiary", "beneficiaries", "stakeholder", "stakeholders",
    "target population",
    "sales", "revenue", "turnover", "income",
    "pricing", "price", "payment", "funding", "grant", "procurement",
    "commercialization", "commercialisation", "business model",
    "competition", "competitive", "competitor", "competitors",
    "cagr", "growth rate"
]


def _looks_like_market_fact(text: str) -> bool:
    """
    Decide whether a fact is clearly market- or business-related.
    This only corrects type labels and does not override risk/mitigation facts.
    """
    if not text:
        return False
    t = text.lower()

    # English keywords
    if any(k in t for k in _MARKET_EN):
        return True

    return False

def _infer_dims_from_text(text: str) -> List[str]:
    """
    Infer dimensions from English keywords when the LLM omits dimensions and type mapping is insufficient.
    This supplements existing labels and does not override dimensions already provided by the model.
    """
    t_lower = (text or "").lower()

    candidates = set()

    # ---- team ----
    team_keywords = [
        "team", "group", "consortium", "partner", "collaborator", "collaboration",
        "researcher", "research team", "project team", "operations team", "delivery team",
        "lead", "leader", "principal investigator", "pi",
        "professor", "director", "expert", "scientist", "researcher", "specialist", "phd", "postdoc",
        "university", "institute", "center", "centre", "laboratory", "lab", "agency", "operator",
        "ceo", "coo", "cto", "cso", "vp", "vice president",
        "founder", "co-founder", "chief executive officer", "manager", "project manager",
    ]
    if any(k in t_lower for k in team_keywords):
        candidates.add("team")

    # ---- objectives ----
    obj_keywords_en = [
        "aim", "aims to", "aimed to",
        "objective", "objectives", "goal", "goals",
        "milestone", "milestones", "endpoint", "endpoints",
        "is designed to", "seeks to", "intends to", "in order to",
    ]
    if any(k in t_lower for k in obj_keywords_en):
        candidates.add("objectives")

    # ---- strategy ----
    strat_keywords_en = [
        "strategy", "strategies", "pathway", "roadmap",
        "commercial", "commercialization", "business model",
        "market entry", "go-to-market", "go to market",
        "market", "market size", "market demand", "market potential",
        "market share", "competitive landscape", "competition", "competitor", "competitors",
        "partnership", "licensing", "co-development",
        "development plan", "regulatory strategy",
    ]

    if any(k in t_lower for k in strat_keywords_en):
        candidates.add("strategy")

    # ---- innovation ----
    inno_keywords_en = [
        "novel", "novelty", "innovative", "innovation",
        "differentiated", "differentiation", "unique",
        "first-in-class", "best-in-class", "state-of-the-art",
        "cutting-edge", "breakthrough", "original", "disruptive",
        "fills the gap", "fill the gap",
    ]
    if any(k in t_lower for k in inno_keywords_en):
        candidates.add("innovation")

    # ---- feasibility ----
    feas_keywords_en = [
        "feasibility", "feasible", "resource", "resources", "infrastructure",
        "budget", "funding", "cost", "costs", "cost-effectiveness",
        "risk", "risks", "challenge", "challenges", "bottleneck", "uncertainty",
        "timeline", "schedule", "timeframe",
        "enrollment", "recruitment", "compliance", "adherence", "burden",
    ]
    if any(k in t_lower for k in feas_keywords_en):
        candidates.add("feasibility")

    # ---- Market-analysis fallback: add strategy/objectives for clearly market-related text ----
    market_keywords_en = [
        "market size", "market", "cagr", "market share", "share of",
        "sales", "revenue", "revenues", "turnover",
        "growth rate", "compound annual growth", "customer", "customers",
        "payer", "payers",
    ]
    if any(k in t_lower for k in market_keywords_en):
        candidates.add("strategy")
        candidates.add("objectives")

    return [d for d in candidates if d in VALID_DIMENSIONS]

def mark_numeric_suspect(fact: Dict[str, Any], chunk_text: str) -> Dict[str, Any]:
    """
    Run a simple validation on facts that contain numbers:
    - Extract numeric fragments from fact.text.
    - If a number does not appear in the source chunk, mark it as possible numeric hallucination.
    - Add meta.suspect_numeric = True/False.
    """
    text = fact.get("text", "") or ""
    nums = re.findall(r"\d+", text)
    if not nums:
        return fact  # No numbers to check.

    chunk_flat = (chunk_text or "").replace(" ", "")
    suspect = False
    for n in nums:
        if n not in chunk_flat:
            suspect = True
            break

    meta = fact.get("meta", {})
    if not isinstance(meta, dict):
        meta = {}
    meta["suspect_numeric"] = suspect
    fact["meta"] = meta
    return fact

def normalize_fact(
    fact: Dict[str, Any],
    proposal_id: str,
    chunk_index: int,
    start: int,
    end: int,
) -> Dict[str, Any]:
    """
    Add metadata to each fact and clean dimensions/type.
    Also supplement dimension labels from type and text so useful information is not dropped.
    """
    text = fact.get("text", "")
    if not isinstance(text, str):
        text = str(text)
    text = _normalize_fact_text(text)

    # Clean raw dimension labels.
    dims = fact.get("dimensions", [])
    if not isinstance(dims, list):
        dims = []
    dims_clean = [d for d in dims if isinstance(d, str) and d in VALID_DIMENSIONS]

    type_val = fact.get("type", "other")
    if type_val not in VALID_TYPES:
        type_val = "other"

    # ===== Auto-correct market facts before type-to-dimensions mapping =====
    # If the LLM did not label a clearly market/business fact as market, force type="market".
    if type_val not in ["market", "risk", "mitigation"]:
        if _looks_like_market_fact(text):
            type_val = "market"

    # Start with existing dimensions, then supplement from type/text.
    dim_set = set(dims_clean)

    # ===== 1. Type-to-dimensions mapping =====
    if type_val in ["team_member", "org_structure"]:
        # Team members and organization structure clearly belong to team.
        dim_set.add("team")

    elif type_val == "collaboration":
        # Collaboration is both team coordination and strategy.
        dim_set.update(["team", "strategy"])

    elif type_val == "pipeline":
        # A pipeline reflects both objectives and strategy.
        dim_set.update(["objectives", "strategy"])

    elif type_val == "milestone":
        # A milestone reflects staged objectives and execution feasibility.
        dim_set.update(["objectives", "feasibility"])

    elif type_val == "clinical_design":
        # Clinical design reflects objective path, strategy, and feasibility.
        dim_set.update(["objectives", "strategy", "feasibility"])

    elif type_val in ["market", "product"]:
        # Market/product facts usually touch commercial strategy and feasibility.
        dim_set.update(["objectives", "strategy", "feasibility"])

    elif type_val in ["tech_route", "regulatory"]:
        # Technical and regulatory routes are strategy and also affect feasibility.
        dim_set.update(["strategy", "feasibility"])

    elif type_val == "funding_source":
        # Funding source affects strategic planning and feasibility.
        dim_set.update(["strategy", "feasibility"])

    elif type_val == "ip_asset":
        # IP assets reflect innovation and longer-term feasibility.
        dim_set.update(["innovation", "feasibility"])

    elif type_val == "evidence":
        # Evidence supports innovation value and feasibility.
        dim_set.update(["innovation", "feasibility"])

    elif type_val == "ai_model":
        # AI models are innovation signals and often part of strategy.
        dim_set.update(["innovation", "strategy"])

    elif type_val in ["resource", "budget_item", "risk", "mitigation"]:
        # Resources, budget, risks, and mitigations primarily affect feasibility.
        dim_set.add("feasibility")

    # ===== 2. If still unlabeled, infer dimensions from text keywords. =====
    if not dim_set:
        inferred = _infer_dims_from_text(text)
        for d in inferred:
            dim_set.add(d)

    # ===== 3. Final fallback: avoid losing the fact completely. =====
    if not dim_set:
        dim_set.add("feasibility")

    priority = ["team", "objectives", "strategy", "innovation", "feasibility"]
    dims_final = [d for d in priority if d in dim_set]

    meta = fact.get("meta", {})
    if not isinstance(meta, dict):
        meta = {}
    meta.update(
        {
            "proposal_id": proposal_id,
            "chunk_index": chunk_index,
            "char_start": start,
            "char_end": end,
        }
    )

    # ==== Compute primary_dimension ====
    primary_dim = None
    if dims_final:
        # Simple priority rule; tune as needed for the business domain.
        # Pick the highest-priority dimension present in dims_final.
        for d in priority:
            if d in dims_final:
                primary_dim = d
                break
        if primary_dim is None:
            primary_dim = dims_final[0]
    else:
        primary_dim = "feasibility"  # This should not happen because of the fallback above.

    return {
        "text": text,
        "dimensions": dims_final,
        "type": type_val,
        "primary_dimension": primary_dim,
        "meta": meta,
    }

def run_extract(proposal_id: str, max_chars: int = 1800, overlap: int = 400):
    stage_start = time.perf_counter()
    full_text = load_full_text(proposal_id)
    _print_input_diagnostics(proposal_id, full_text, max_chars=max_chars, overlap=overlap)
    chunks = make_chunks(full_text, max_chars=max_chars, overlap=overlap)
    _print_chunk_plan(chunks)

    out_dir = EXTRACTED_DIR / proposal_id
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "raw_facts.jsonl"
    audit_path = out_dir / "stage1_audit.json"

    total_facts = 0
    deduped_exact_facts = 0
    # Track fact counts per dimension for sanity checks.
    dim_counts = {dim: 0 for dim in VALID_DIMENSIONS}
    type_counts = {typ: 0 for typ in VALID_TYPES}
    primary_dim_counts = {dim: 0 for dim in VALID_DIMENSIONS}
    suspect_numeric_count = 0
    chunk_audit = []

    def process_chunk(ch: Dict[str, Any]) -> Dict[str, Any]:
        chunk_start = time.perf_counter()
        idx = ch["index"]
        chunk_len = ch["end"] - ch["start"]
        _log(
            "CHUNK",
            f"start chunk={idx+1}/{len(chunks)} range={ch['start']}:{ch['end']} "
            f"chars={chunk_len}"
        )
        _log("PREVIEW", f"chunk={idx+1} text_preview={_preview_text(ch['text'])}")
        chunk_trace = {
            "chunk_index": idx,
            "chunk_number": idx + 1,
            "char_start": ch["start"],
            "char_end": ch["end"],
            "char_len": chunk_len,
            "preview": _preview_text(ch["text"]),
            "llm_calls": [],
            "dense_retry_triggered": False,
            "dense_retry_used": False,
        }

        # First normal extraction pass.
        data = call_llm_for_chunk(ch["text"], trace=chunk_trace)
        facts = data.get("facts", [])
        if not isinstance(facts, list):
            facts = []
        chunk_trace["raw_fact_count"] = len(facts)

        # If a long chunk produces too few facts, try one dense retry.
        if chunk_len >= 1200 and len(facts) < 5:
            chunk_trace["dense_retry_triggered"] = True
            _log(
                "WARN",
                f"chunk={idx+1} long chunk produced few facts "
                f"(chars={chunk_len}, raw_facts={len(facts)}); trying dense retry"
            )
            dense_data = call_llm_for_chunk(ch["text"], dense=True, trace=chunk_trace)
            dense_facts = dense_data.get("facts", [])
            if isinstance(dense_facts, list) and len(dense_facts) > len(facts):
                _log(
                    "CHUNK",
                    f"chunk={idx+1} dense retry improved facts "
                    f"normal={len(facts)} dense={len(dense_facts)}; using dense result"
                )
                facts = dense_facts
                chunk_trace["dense_retry_used"] = True
            else:
                _log(
                    "CHUNK",
                    f"chunk={idx+1} dense retry did not improve facts "
                    f"normal={len(facts)} dense={len(dense_facts) if isinstance(dense_facts, list) else 'invalid'}; "
                    f"keeping normal result"
                )
            chunk_trace["dense_fact_count"] = len(dense_facts) if isinstance(dense_facts, list) else 0

        normalized_list = []
        skipped_non_dict = 0
        skipped_empty_text = 0
        skipped_duplicate_text = 0
        for fact in facts:
            if not isinstance(fact, dict):
                skipped_non_dict += 1
                continue

            # Mark possible numeric hallucinations using the source chunk.
            fact = mark_numeric_suspect(fact, ch["text"])

            norm = normalize_fact(
                fact,
                proposal_id=proposal_id,
                chunk_index=idx,
                start=ch["start"],
                end=ch["end"],
            )

            # Drop empty fact text.
            fact_text = norm["text"]
            if fact_text:
                normalized_list.append(norm)
            else:
                skipped_empty_text += 1

        dist = _fact_distribution(normalized_list)
        chunk_trace.update(
            {
                "written_fact_count": len(normalized_list),
                "skipped_non_dict": skipped_non_dict,
                "skipped_empty_text": skipped_empty_text,
                "skipped_duplicate_text": skipped_duplicate_text,
                "elapsed_sec": round(time.perf_counter() - chunk_start, 2),
                "distribution": dist,
                "fact_previews": [_preview_text(f.get("text", ""), 220) for f in normalized_list[:5]],
            }
        )
        return {
            "idx": idx,
            "chunk_len": chunk_len,
            "normalized_list": normalized_list,
            "chunk_trace": chunk_trace,
            "dist": dist,
        }

    _write_progress(0, len(chunks), proposal_id)
    chunk_workers = _bounded_worker_count(STAGE1_CHUNK_WORKERS, 1, len(chunks))
    _log("CONCURRENCY", f"stage1_chunks workers={chunk_workers} chunks={len(chunks)}")
    chunk_results: Dict[int, Dict[str, Any]] = {}
    completed_chunks = 0
    if chunk_workers > 1:
        with ThreadPoolExecutor(max_workers=chunk_workers) as pool:
            future_map = {pool.submit(process_chunk, ch): ch["index"] for ch in chunks}
            for future in as_completed(future_map):
                result = future.result()
                chunk_results[result["idx"]] = result
                completed_chunks += 1
                _write_progress(completed_chunks, len(chunks), proposal_id)
                _log(
                    "CHUNK",
                    f"completed chunk={result['idx']+1}/{len(chunks)} "
                    f"completed_chunks={completed_chunks}/{len(chunks)} "
                    f"elapsed_sec={result['chunk_trace']['elapsed_sec']}"
                )
    else:
        for ch in chunks:
            result = process_chunk(ch)
            chunk_results[result["idx"]] = result
            completed_chunks += 1
            _write_progress(completed_chunks, len(chunks), proposal_id)

    written_fact_keys = set()

    with out_path.open("w", encoding="utf-8") as f_out:
        for idx in sorted(chunk_results):
            result = chunk_results[idx]
            normalized_list = result["normalized_list"]
            chunk_trace = result["chunk_trace"]
            chunk_len = result["chunk_len"]
            written_list = []

            for fact in normalized_list:
                if DEDUP_EXACT_FACTS:
                    fact_key = (
                        _normalize_fact_text(fact.get("text", "")).lower(),
                        fact.get("type", "other"),
                        tuple(sorted(fact.get("dimensions", []))),
                    )
                    if fact_key in written_fact_keys:
                        deduped_exact_facts += 1
                        chunk_trace["skipped_duplicate_text"] = chunk_trace.get("skipped_duplicate_text", 0) + 1
                        continue
                    written_fact_keys.add(fact_key)
                written_list.append(fact)

            dist = _fact_distribution(written_list)
            chunk_trace["written_fact_count"] = len(written_list)
            chunk_trace["distribution"] = dist
            chunk_trace["fact_previews"] = [_preview_text(f.get("text", ""), 220) for f in written_list[:5]]

            for fact in written_list:
                f_out.write(json.dumps(fact, ensure_ascii=False) + "\n")
                total_facts += 1
                # Update distribution counters.
                for d in fact.get("dimensions", []):
                    if d in dim_counts:
                        dim_counts[d] += 1
                fact_type = fact.get("type", "other")
                if fact_type in type_counts:
                    type_counts[fact_type] += 1
                primary_dim = fact.get("primary_dimension", "")
                if primary_dim in primary_dim_counts:
                    primary_dim_counts[primary_dim] += 1
                if fact.get("meta", {}).get("suspect_numeric"):
                    suspect_numeric_count += 1

            chunk_audit.append(chunk_trace)
            if len(written_list) < LOW_FACT_WARN_THRESHOLD and chunk_len >= 500:
                _log(
                    "WARN",
                    f"chunk={idx+1} wrote only {len(written_list)} fact(s) from {chunk_len} chars; "
                    f"inspect this chunk in stage1_audit.json"
                )
            _log(
                "CHUNK",
                f"done chunk={idx+1}/{len(chunks)} raw_facts={chunk_trace.get('raw_fact_count', 0)} "
                f"written_facts={len(written_list)} cumulative_facts={total_facts} "
                f"elapsed_sec={chunk_trace['elapsed_sec']}"
            )
            _log("CHUNK", f"chunk={idx+1} dims={json.dumps(dist['dimensions'], ensure_ascii=False)}")
            _log("CHUNK", f"chunk={idx+1} types={json.dumps(dist['types'], ensure_ascii=False)}")
            if dist["suspect_numeric"]["count"]:
                _log("WARN", f"chunk={idx+1} suspect_numeric_facts={dist['suspect_numeric']['count']}")

    elapsed_total = time.perf_counter() - stage_start
    _log("OK", f"raw facts written path={out_path} total_facts={total_facts}")
    if DEDUP_EXACT_FACTS:
        _log("SUMMARY", f"deduped_exact_facts={deduped_exact_facts}")

    # ===== Global dimension distribution check =====
    _log("SUMMARY", "dimension distribution based on raw_facts.jsonl")
    for dim in VALID_DIMENSIONS:
        _log("SUMMARY", f"{dim}={dim_counts[dim]} facts")
    _log("SUMMARY", f"primary_dimension_counts={json.dumps(primary_dim_counts, ensure_ascii=False)}")
    _log("SUMMARY", f"type_counts={json.dumps(type_counts, ensure_ascii=False)}")
    _log("SUMMARY", f"suspect_numeric_facts={suspect_numeric_count}")
    _log("SUMMARY", f"elapsed_sec={elapsed_total:.2f}")

    # Simple sanity check: warn if any dimension is unusually sparse. This does not stop the run.
    if total_facts > 0:
        avg = total_facts / len(VALID_DIMENSIONS)
        for dim in VALID_DIMENSIONS:
            if dim_counts[dim] < max(8, 0.25 * avg):
                _log(
                    "WARN",
                    f"dimension={dim} has only {dim_counts[dim]} facts, below average={avg:.1f}; "
                    f"check raw_facts.jsonl and stage1_audit.json"
                )
    else:
        _log("WARN", "Stage 1 produced zero facts.")

    audit = {
        "proposal_id": proposal_id,
        "model": OPENAI_MODEL,
        "input_path": str((PREPARED_DIR / proposal_id / "full_text.txt").resolve()),
        "output_path": str(out_path.resolve()),
        "max_chars": max_chars,
        "overlap": overlap,
        "chunk_workers": chunk_workers,
        "input_chars": len(full_text),
        "chunk_count": len(chunks),
        "total_facts": total_facts,
        "deduped_exact_facts": deduped_exact_facts,
        "elapsed_sec": round(elapsed_total, 2),
        "dimension_counts": dim_counts,
        "primary_dimension_counts": primary_dim_counts,
        "type_counts": type_counts,
        "suspect_numeric_facts": suspect_numeric_count,
        "chunks": chunk_audit,
    }
    audit_path.write_text(json.dumps(audit, ensure_ascii=False, indent=2), encoding="utf-8")
    _log("OK", f"stage1_audit.json written path={audit_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Stage 1: extract atomic facts by chunk (raw_facts.jsonl)"
    )
    parser.add_argument(
        "--proposal_id",
        required=False,
        help="Proposal ID corresponding to src/data/prepared/<proposal_id>",
    )
    parser.add_argument(
        "--max_chars",
        type=int,
        default=1800,
        help="Maximum characters per chunk (default: 1800)",
    )
    parser.add_argument(
        "--overlap",
        type=int,
        default=400,
        help="Character overlap between chunks (default: 400)",
    )
    args = parser.parse_args()

    if args.proposal_id:
        pid = args.proposal_id
    else:
        pid = find_latest_prepared_proposal()

    run_extract(pid, max_chars=args.max_chars, overlap=args.overlap)


if __name__ == "__main__":
    main()
